// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: analytic/analytic_message.proto

package analytic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteCapturedRecordsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCapturedRecordsReq) Reset() {
	*x = DeleteCapturedRecordsReq{}
	mi := &file_analytic_analytic_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCapturedRecordsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCapturedRecordsReq) ProtoMessage() {}

func (x *DeleteCapturedRecordsReq) ProtoReflect() protoreflect.Message {
	mi := &file_analytic_analytic_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCapturedRecordsReq.ProtoReflect.Descriptor instead.
func (*DeleteCapturedRecordsReq) Descriptor() ([]byte, []int) {
	return file_analytic_analytic_message_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteCapturedRecordsReq) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type DeleteCapturedRecordsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCapturedRecordsResp) Reset() {
	*x = DeleteCapturedRecordsResp{}
	mi := &file_analytic_analytic_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCapturedRecordsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCapturedRecordsResp) ProtoMessage() {}

func (x *DeleteCapturedRecordsResp) ProtoReflect() protoreflect.Message {
	mi := &file_analytic_analytic_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCapturedRecordsResp.ProtoReflect.Descriptor instead.
func (*DeleteCapturedRecordsResp) Descriptor() ([]byte, []int) {
	return file_analytic_analytic_message_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteCapturedRecordsResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_analytic_analytic_message_proto protoreflect.FileDescriptor

const file_analytic_analytic_message_proto_rawDesc = "" +
	"\n" +
	"\x1fanalytic/analytic_message.proto\x12\banalytic\"9\n" +
	"\x18DeleteCapturedRecordsReq\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\"5\n" +
	"\x19DeleteCapturedRecordsResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB\x1dZ\x1btenkhours/proto/pb/analyticb\x06proto3"

var (
	file_analytic_analytic_message_proto_rawDescOnce sync.Once
	file_analytic_analytic_message_proto_rawDescData []byte
)

func file_analytic_analytic_message_proto_rawDescGZIP() []byte {
	file_analytic_analytic_message_proto_rawDescOnce.Do(func() {
		file_analytic_analytic_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytic_analytic_message_proto_rawDesc), len(file_analytic_analytic_message_proto_rawDesc)))
	})
	return file_analytic_analytic_message_proto_rawDescData
}

var file_analytic_analytic_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_analytic_analytic_message_proto_goTypes = []any{
	(*DeleteCapturedRecordsReq)(nil),  // 0: analytic.DeleteCapturedRecordsReq
	(*DeleteCapturedRecordsResp)(nil), // 1: analytic.DeleteCapturedRecordsResp
}
var file_analytic_analytic_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_analytic_analytic_message_proto_init() }
func file_analytic_analytic_message_proto_init() {
	if File_analytic_analytic_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytic_analytic_message_proto_rawDesc), len(file_analytic_analytic_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_analytic_analytic_message_proto_goTypes,
		DependencyIndexes: file_analytic_analytic_message_proto_depIdxs,
		MessageInfos:      file_analytic_analytic_message_proto_msgTypes,
	}.Build()
	File_analytic_analytic_message_proto = out.File
	file_analytic_analytic_message_proto_goTypes = nil
	file_analytic_analytic_message_proto_depIdxs = nil
}
