// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: analytic/analytic_service.proto

package analytic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_analytic_analytic_service_proto protoreflect.FileDescriptor

const file_analytic_analytic_service_proto_rawDesc = "" +
	"\n" +
	"\x1fanalytic/analytic_service.proto\x12\banalytic\x1a\x1fanalytic/analytic_message.proto2n\n" +
	"\bAnalytic\x12b\n" +
	"\x15DeleteCapturedRecords\x12\".analytic.DeleteCapturedRecordsReq\x1a#.analytic.DeleteCapturedRecordsResp\"\x00B\x1dZ\x1btenkhours/proto/pb/analyticb\x06proto3"

var file_analytic_analytic_service_proto_goTypes = []any{
	(*DeleteCapturedRecordsReq)(nil),  // 0: analytic.DeleteCapturedRecordsReq
	(*DeleteCapturedRecordsResp)(nil), // 1: analytic.DeleteCapturedRecordsResp
}
var file_analytic_analytic_service_proto_depIdxs = []int32{
	0, // 0: analytic.Analytic.DeleteCapturedRecords:input_type -> analytic.DeleteCapturedRecordsReq
	1, // 1: analytic.Analytic.DeleteCapturedRecords:output_type -> analytic.DeleteCapturedRecordsResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_analytic_analytic_service_proto_init() }
func file_analytic_analytic_service_proto_init() {
	if File_analytic_analytic_service_proto != nil {
		return
	}
	file_analytic_analytic_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytic_analytic_service_proto_rawDesc), len(file_analytic_analytic_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytic_analytic_service_proto_goTypes,
		DependencyIndexes: file_analytic_analytic_service_proto_depIdxs,
	}.Build()
	File_analytic_analytic_service_proto = out.File
	file_analytic_analytic_service_proto_goTypes = nil
	file_analytic_analytic_service_proto_depIdxs = nil
}
