package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"tenkhours/services/timetracking/entity"
	"time"
)

// CreateTimeTracking is the resolver for the createTimeTracking field.
func (r *mutationResolver) CreateTimeTracking(ctx context.Context, characterID string, categoryID *string, startTime time.Time) (*entity.TimeTracking, error) {
	return r.TimeTrackingBusiness.CreateTimeTracking(ctx, characterID, categoryID, startTime)
}

// UpdateTimeTracking is the resolver for the updateTimeTracking field.
func (r *mutationResolver) UpdateTimeTracking(ctx context.Context) (*entity.TimeTrackingWithFish, error) {
	timeTracking, fishData, err := r.TimeTrackingBusiness.UpdateTimeTracking(ctx)
	if err != nil {
		return nil, err
	}

	return &entity.TimeTrackingWithFish{
		TimeTracking: timeTracking,
		Normal:       int(fishData.Normal),
		Gold:         int(fishData.Gold),
	}, nil
}

// CurrentTimeTracking is the resolver for the currentTimeTracking field.
func (r *queryResolver) CurrentTimeTracking(ctx context.Context) (*entity.TimeTracking, error) {
	return r.TimeTrackingBusiness.GetCurrentTimeTracking(ctx)
}

// TotalCurrentTimeTracking is the resolver for the totalCurrentTimeTracking field.
func (r *queryResolver) TotalCurrentTimeTracking(ctx context.Context, characterID string, timestamp time.Time) (int, error) {
	return r.TimeTrackingBusiness.GetTotalCurrentTimeTracking(ctx, characterID, timestamp)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
