// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Fish struct {
	ID        string `json:"id"`
	ProfileID string `json:"profileID"`
	// Numbers of different fish types.
	Gold   *int `json:"gold,omitempty"`
	Normal *int `json:"normal,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Rod struct {
	ID        string `json:"id"`
	ProfileID string `json:"profileID"`
	// Type of rod: can be get reward related to this(e.g. Yellow cod can make character hair's color turn to yellow)
	Type *string `json:"type,omitempty"`
}

// Input for creating or updating rod
type RodInput struct {
	// Type of rod
	Type *string `json:"type,omitempty"`
}
