// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

type Mutation struct {
}

type Query struct {
}

type Rod struct {
	ID        primitive.ObjectID `json:"id"`
	ProfileID primitive.ObjectID `json:"profileID"`
	// Type of rod: can be get reward related to this(e.g. Yellow rod can make character hair's color turn to yellow)
	Type *string `json:"type,omitempty"`
}

// Input for creating or updating rod
type RodInput struct {
	// Type of rod
	Type *string `json:"type,omitempty"`
}

type FishType string

const (
	FishTypeNormal FishType = "normal"
	FishTypeGold   FishType = "gold"
)

var AllFishType = []FishType{
	FishTypeNormal,
	FishTypeGold,
}

func (e FishType) IsValid() bool {
	switch e {
	case FishTypeNormal, FishTypeGold:
		return true
	}
	return false
}

func (e FishType) String() string {
	return string(e)
}

func (e *FishType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FishType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FishType", str)
	}
	return nil
}

func (e FishType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
