// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cod struct {
	ID        string `json:"id"`
	ProfileID string `json:"profileID"`
	// Type of cod: can be get reward related to this(e.g. Yellow cod can make character hair's color turn to yellow)
	Type *string `json:"type,omitempty"`
}

// Input for creating or updating cod
type CodInput struct {
	// Type of cod
	Type *string `json:"type,omitempty"`
}

type Fish struct {
	ID        string `json:"id"`
	ProfileID string `json:"profileID"`
	// An object representing the counts of different fish types.
	Counts *FishCounts `json:"counts"`
}

// Represents the counts of various fish types.
type FishCounts struct {
	Gold   *int `json:"gold,omitempty"`
	Normal *int `json:"normal,omitempty"`
}

// Input for creating or updating fish counts.
type FishInput struct {
	Gold   *int `json:"gold,omitempty"`
	Normal *int `json:"normal,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
