package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"encoding/json"
	"fmt"
	"tenkhours/services/analytics/graph/model"
	"time"

	"github.com/samber/lo"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// CreateSnapshot is the resolver for the createSnapshot field.
func (r *mutationResolver) CreateSnapshot(ctx context.Context, characterID primitive.ObjectID, description *string) (*model.Snapshot, error) {
	snapshot, err := r.CharactersBusiness.CreateNewSnapshot(ctx, characterID, description)
	if err != nil {
		return nil, fmt.Errorf("failed to create snapshot: %v", err)
	}

	return MapToSnapshotDto(snapshot), nil
}

// CreateCapturedRecord is the resolver for the createCapturedRecord field.
func (r *mutationResolver) CreateCapturedRecord(ctx context.Context, characterID primitive.ObjectID) (*model.CapturedRecord, error) {
	return r.CharactersBusiness.CreateCapturedRecord(ctx, characterID)
}

// Snapshots is the resolver for the snapshots field.
func (r *queryResolver) Snapshots(ctx context.Context, characterID *primitive.ObjectID, filter *model.DateTimeFilter) ([]model.Snapshot, error) {
	snapshots, err := r.CharactersBusiness.GetSnapshots(ctx, characterID, filter)
	if err != nil {
		return nil, fmt.Errorf("failed to get snapshots: %v", err)
	}

	var res []model.Snapshot
	for _, snapshot := range snapshots {
		res = append(res, *MapToSnapshotDto(&snapshot))
	}

	return res, nil
}

// AnalyticResults is the resolver for the analyticResults field.
func (r *queryResolver) AnalyticResults(ctx context.Context, characterID *primitive.ObjectID, startTime *time.Time, endTime *time.Time, analyticSections []model.AnalyticSection, captureRecordLocals *string) (map[string]interface{}, error) {
	// Decode json string to capture records
	decodedCaptureRecordLocals := make([]model.CapturedRecord, 0)
	if captureRecordLocals != nil {
		if err := json.Unmarshal([]byte(*captureRecordLocals), &decodedCaptureRecordLocals); err != nil {
			return nil, fmt.Errorf("failed to unmarshal capture records: %v", err)
		}
	}

	if startTime != nil && endTime != nil && startTime.After(*endTime) {
		return nil, fmt.Errorf("start time must be before end time")
	}

	if lo.Contains(analyticSections, model.AnalyticSectionFrequency) {
		if startTime == nil || endTime == nil {
			return nil, fmt.Errorf("start time and end time are required for frequency analytic section")
		}

		// Check if the time range is under 1 year
		if endTime.Sub(*startTime) > time.Hour*24*366 {
			return nil, fmt.Errorf("time range must be under 1 year")
		}
	}

	return r.CharactersBusiness.GetAnalyticResults(ctx, characterID, startTime, endTime, analyticSections, decodedCaptureRecordLocals)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
