package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"tenkhours/services/analytics/graph/model"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// CreateSnapshot is the resolver for the createSnapshot field.
func (r *mutationResolver) CreateSnapshot(ctx context.Context, characterID primitive.ObjectID, description *string) (*model.Snapshot, error) {
	snapshot, err := r.CharactersHandler.CreateNewSnapshot(ctx, characterID, description)
	if err != nil {
		return nil, fmt.Errorf("failed to create snapshot: %v", err)
	}

	return MapToSnapshotDto(snapshot), nil
}

// CreateCapturedRecord is the resolver for the createCapturedRecord field.
func (r *mutationResolver) CreateCapturedRecord(ctx context.Context, characterID primitive.ObjectID) (*model.CapturedRecord, error) {
	return r.CharactersHandler.CreateCapturedRecord(ctx, characterID)
}

// Snapshots is the resolver for the snapshots field.
func (r *queryResolver) Snapshots(ctx context.Context, characterID *primitive.ObjectID, filter *model.Filter) ([]model.Snapshot, error) {
	snapshots, err := r.CharactersHandler.GetSnapshots(ctx, characterID, filter)
	if err != nil {
		return nil, fmt.Errorf("failed to get snapshots: %v", err)
	}

	var res []model.Snapshot
	for _, snapshot := range snapshots {
		res = append(res, *MapToSnapshotDto(&snapshot))
	}

	return res, nil
}

// AnalyticResults is the resolver for the analyticResults field.
func (r *queryResolver) AnalyticResults(ctx context.Context, characterID *primitive.ObjectID, filter *model.Filter) (map[string]interface{}, error) {
	return r.CharactersHandler.GetAnalyticResults(ctx, characterID, filter)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }