// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v3.21.12
// source: timetracking/timetracking_message.proto

package timetracking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimeTracking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CharacterId   string                 `protobuf:"bytes,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	CategoryId    *string                `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *int64                 `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeTracking) Reset() {
	*x = TimeTracking{}
	mi := &file_timetracking_timetracking_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeTracking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeTracking) ProtoMessage() {}

func (x *TimeTracking) ProtoReflect() protoreflect.Message {
	mi := &file_timetracking_timetracking_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeTracking.ProtoReflect.Descriptor instead.
func (*TimeTracking) Descriptor() ([]byte, []int) {
	return file_timetracking_timetracking_message_proto_rawDescGZIP(), []int{0}
}

func (x *TimeTracking) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TimeTracking) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *TimeTracking) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *TimeTracking) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TimeTracking) GetEndTime() int64 {
	if x != nil && x.EndTime != nil {
		return *x.EndTime
	}
	return 0
}

type TimeTrackingWithFish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeTracking  *TimeTracking          `protobuf:"bytes,1,opt,name=time_tracking,json=timeTracking,proto3" json:"time_tracking,omitempty"`
	Normal        int32                  `protobuf:"varint,2,opt,name=normal,proto3" json:"normal,omitempty"`
	Gold          int32                  `protobuf:"varint,3,opt,name=gold,proto3" json:"gold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeTrackingWithFish) Reset() {
	*x = TimeTrackingWithFish{}
	mi := &file_timetracking_timetracking_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeTrackingWithFish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeTrackingWithFish) ProtoMessage() {}

func (x *TimeTrackingWithFish) ProtoReflect() protoreflect.Message {
	mi := &file_timetracking_timetracking_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeTrackingWithFish.ProtoReflect.Descriptor instead.
func (*TimeTrackingWithFish) Descriptor() ([]byte, []int) {
	return file_timetracking_timetracking_message_proto_rawDescGZIP(), []int{1}
}

func (x *TimeTrackingWithFish) GetTimeTracking() *TimeTracking {
	if x != nil {
		return x.TimeTracking
	}
	return nil
}

func (x *TimeTrackingWithFish) GetNormal() int32 {
	if x != nil {
		return x.Normal
	}
	return 0
}

func (x *TimeTrackingWithFish) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

type TotalTimeTrackingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TotalTimeTrackingRequest) Reset() {
	*x = TotalTimeTrackingRequest{}
	mi := &file_timetracking_timetracking_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalTimeTrackingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalTimeTrackingRequest) ProtoMessage() {}

func (x *TotalTimeTrackingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timetracking_timetracking_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalTimeTrackingRequest.ProtoReflect.Descriptor instead.
func (*TotalTimeTrackingRequest) Descriptor() ([]byte, []int) {
	return file_timetracking_timetracking_message_proto_rawDescGZIP(), []int{2}
}

func (x *TotalTimeTrackingRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *TotalTimeTrackingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TotalTimeTrackingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalTime     int32                  `protobuf:"varint,1,opt,name=total_time,json=totalTime,proto3" json:"total_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TotalTimeTrackingResponse) Reset() {
	*x = TotalTimeTrackingResponse{}
	mi := &file_timetracking_timetracking_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalTimeTrackingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalTimeTrackingResponse) ProtoMessage() {}

func (x *TotalTimeTrackingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timetracking_timetracking_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalTimeTrackingResponse.ProtoReflect.Descriptor instead.
func (*TotalTimeTrackingResponse) Descriptor() ([]byte, []int) {
	return file_timetracking_timetracking_message_proto_rawDescGZIP(), []int{3}
}

func (x *TotalTimeTrackingResponse) GetTotalTime() int32 {
	if x != nil {
		return x.TotalTime
	}
	return 0
}

type CreateTimeTrackingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	CategoryId    *string                `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTimeTrackingRequest) Reset() {
	*x = CreateTimeTrackingRequest{}
	mi := &file_timetracking_timetracking_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTimeTrackingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTimeTrackingRequest) ProtoMessage() {}

func (x *CreateTimeTrackingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timetracking_timetracking_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTimeTrackingRequest.ProtoReflect.Descriptor instead.
func (*CreateTimeTrackingRequest) Descriptor() ([]byte, []int) {
	return file_timetracking_timetracking_message_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTimeTrackingRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *CreateTimeTrackingRequest) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *CreateTimeTrackingRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

var File_timetracking_timetracking_message_proto protoreflect.FileDescriptor

var file_timetracking_timetracking_message_proto_rawDesc = []byte{
	0x0a, 0x27, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x22, 0xc3, 0x01, 0x0a, 0x0c, 0x54, 0x69, 0x6d, 0x65,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72,
	0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0b, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x88, 0x01,
	0x01, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x48, 0x01, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x88, 0x01, 0x01,
	0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64,
	0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x83, 0x01,
	0x0a, 0x14, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x57, 0x69,
	0x74, 0x68, 0x46, 0x69, 0x73, 0x68, 0x12, 0x3f, 0x0a, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x74, 0x69, 0x6d, 0x65, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x54,
	0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x72, 0x6d, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x67,
	0x6f, 0x6c, 0x64, 0x22, 0x5b, 0x0a, 0x18, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65,
	0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x22, 0x3a, 0x0a, 0x19, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x72, 0x61,
	0x63, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x93, 0x01, 0x0a,
	0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x72, 0x61, 0x63, 0x6b,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a,
	0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64,
	0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f,
	0x69, 0x64, 0x42, 0x1e, 0x5a, 0x1c, 0x74, 0x65, 0x6e, 0x6b, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69,
	0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_timetracking_timetracking_message_proto_rawDescOnce sync.Once
	file_timetracking_timetracking_message_proto_rawDescData = file_timetracking_timetracking_message_proto_rawDesc
)

func file_timetracking_timetracking_message_proto_rawDescGZIP() []byte {
	file_timetracking_timetracking_message_proto_rawDescOnce.Do(func() {
		file_timetracking_timetracking_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_timetracking_timetracking_message_proto_rawDescData)
	})
	return file_timetracking_timetracking_message_proto_rawDescData
}

var file_timetracking_timetracking_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_timetracking_timetracking_message_proto_goTypes = []any{
	(*TimeTracking)(nil),              // 0: timetracking.TimeTracking
	(*TimeTrackingWithFish)(nil),      // 1: timetracking.TimeTrackingWithFish
	(*TotalTimeTrackingRequest)(nil),  // 2: timetracking.TotalTimeTrackingRequest
	(*TotalTimeTrackingResponse)(nil), // 3: timetracking.TotalTimeTrackingResponse
	(*CreateTimeTrackingRequest)(nil), // 4: timetracking.CreateTimeTrackingRequest
}
var file_timetracking_timetracking_message_proto_depIdxs = []int32{
	0, // 0: timetracking.TimeTrackingWithFish.time_tracking:type_name -> timetracking.TimeTracking
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_timetracking_timetracking_message_proto_init() }
func file_timetracking_timetracking_message_proto_init() {
	if File_timetracking_timetracking_message_proto != nil {
		return
	}
	file_timetracking_timetracking_message_proto_msgTypes[0].OneofWrappers = []any{}
	file_timetracking_timetracking_message_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_timetracking_timetracking_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_timetracking_timetracking_message_proto_goTypes,
		DependencyIndexes: file_timetracking_timetracking_message_proto_depIdxs,
		MessageInfos:      file_timetracking_timetracking_message_proto_msgTypes,
	}.Build()
	File_timetracking_timetracking_message_proto = out.File
	file_timetracking_timetracking_message_proto_rawDesc = nil
	file_timetracking_timetracking_message_proto_goTypes = nil
	file_timetracking_timetracking_message_proto_depIdxs = nil
}
