// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"tenkhours/services/core/repo"
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

type CapturedRecord struct {
	ID               primitive.ObjectID           `json:"id" bson:"_id,omitempty"`
	Timestamp        time.Time                    `json:"timestamp" bson:"timestamp,omitempty"`
	TotalFocusedTime int32                        `json:"totalFocusedTime" bson:"total_focused_time,omitempty"`
	CustomMetrics    []CapturedRecordCustomMetric `json:"customMetrics,omitempty" bson:"custom_metrics,omitempty"`
	TimeTrackings    []CapturedRecordTimeTracking `json:"timeTrackings,omitempty" bson:"time_trackings,omitempty"`
	Metadata         CapturedRecordMetadata       `json:"metadata" bson:"metadata,omitempty"`
}

type CapturedRecordCustomMetric struct {
	ID   primitive.ObjectID `json:"id" bson:"_id,omitempty"`
	Time int32              `json:"time" bson:"time,omitempty"`
}

type CapturedRecordMetadata struct {
	CharacterID primitive.ObjectID `json:"characterID" bson:"character_id,omitempty"`
	ProfileID   primitive.ObjectID `json:"profileID" bson:"profile_id,omitempty"`
}

type CapturedRecordTimeTracking struct {
	CustomMetricID primitive.ObjectID `json:"customMetricID" bson:"custom_metric_id,omitempty"`
	Time           int32              `json:"time" bson:"time,omitempty"`
	StartTime      time.Time          `json:"startTime" bson:"start_time,omitempty"`
	EndTime        time.Time          `json:"endTime" bson:"end_time,omitempty"`
}

type DateTimeFilter struct {
	Month *Month `json:"month,omitempty"`
	Year  *int32 `json:"year,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Snapshot struct {
	ID          primitive.ObjectID `json:"id"`
	Timestamp   time.Time          `json:"timestamp"`
	Character   SnapshotCharacter  `json:"character"`
	Description string             `json:"description"`
}

type SnapshotCharacter struct {
	ID               primitive.ObjectID     `json:"id"`
	ProfileID        primitive.ObjectID     `json:"profileID"`
	Name             string                 `json:"name"`
	Gender           bool                   `json:"gender"`
	Tags             []string               `json:"tags"`
	TotalFocusedTime int32                  `json:"totalFocusedTime"`
	CustomMetrics    []SnapshotCustomMetric `json:"customMetrics"`
}

type SnapshotCustomMetric struct {
	ID          primitive.ObjectID       `json:"id"`
	Name        string                   `json:"name"`
	Description string                   `json:"description"`
	Time        int32                    `json:"time"`
	Style       SnapshotMetricStyle      `json:"style"`
	Properties  []SnapshotMetricProperty `json:"properties"`
}

type SnapshotMetricProperty struct {
	ID    primitive.ObjectID      `json:"id"`
	Name  string                  `json:"name"`
	Type  repo.MetricPropertyType `json:"type"`
	Value string                  `json:"value"`
	Unit  string                  `json:"unit"`
}

type SnapshotMetricStyle struct {
	Color string `json:"color"`
	Icon  string `json:"icon"`
}

type AnalyticSection string

const (
	AnalyticSectionOverall      AnalyticSection = "Overall"
	AnalyticSectionDistribution AnalyticSection = "Distribution"
	AnalyticSectionTimeline     AnalyticSection = "Timeline"
	AnalyticSectionFrequency    AnalyticSection = "Frequency"
)

var AllAnalyticSection = []AnalyticSection{
	AnalyticSectionOverall,
	AnalyticSectionDistribution,
	AnalyticSectionTimeline,
	AnalyticSectionFrequency,
}

func (e AnalyticSection) IsValid() bool {
	switch e {
	case AnalyticSectionOverall, AnalyticSectionDistribution, AnalyticSectionTimeline, AnalyticSectionFrequency:
		return true
	}
	return false
}

func (e AnalyticSection) String() string {
	return string(e)
}

func (e *AnalyticSection) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AnalyticSection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AnalyticSection", str)
	}
	return nil
}

func (e AnalyticSection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Month string

const (
	MonthJanuary   Month = "January"
	MonthFebruary  Month = "February"
	MonthMarch     Month = "March"
	MonthApril     Month = "April"
	MonthMay       Month = "May"
	MonthJune      Month = "June"
	MonthJuly      Month = "July"
	MonthAugust    Month = "August"
	MonthSeptember Month = "September"
	MonthOctober   Month = "October"
	MonthNovember  Month = "November"
	MonthDecember  Month = "December"
)

var AllMonth = []Month{
	MonthJanuary,
	MonthFebruary,
	MonthMarch,
	MonthApril,
	MonthMay,
	MonthJune,
	MonthJuly,
	MonthAugust,
	MonthSeptember,
	MonthOctober,
	MonthNovember,
	MonthDecember,
}

func (e Month) IsValid() bool {
	switch e {
	case MonthJanuary, MonthFebruary, MonthMarch, MonthApril, MonthMay, MonthJune, MonthJuly, MonthAugust, MonthSeptember, MonthOctober, MonthNovember, MonthDecember:
		return true
	}
	return false
}

func (e Month) String() string {
	return string(e)
}

func (e *Month) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Month(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Month", str)
	}
	return nil
}

func (e Month) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Weekday string

const (
	WeekdaySunday    Weekday = "Sunday"
	WeekdayMonday    Weekday = "Monday"
	WeekdayTuesday   Weekday = "Tuesday"
	WeekdayWednesday Weekday = "Wednesday"
	WeekdayThursday  Weekday = "Thursday"
	WeekdayFriday    Weekday = "Friday"
	WeekdaySaturday  Weekday = "Saturday"
)

var AllWeekday = []Weekday{
	WeekdaySunday,
	WeekdayMonday,
	WeekdayTuesday,
	WeekdayWednesday,
	WeekdayThursday,
	WeekdayFriday,
	WeekdaySaturday,
}

func (e Weekday) IsValid() bool {
	switch e {
	case WeekdaySunday, WeekdayMonday, WeekdayTuesday, WeekdayWednesday, WeekdayThursday, WeekdayFriday, WeekdaySaturday:
		return true
	}
	return false
}

func (e Weekday) String() string {
	return string(e)
}

func (e *Weekday) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Weekday(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Weekday", str)
	}
	return nil
}

func (e Weekday) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
