// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: currency/currency_service.proto

package currency

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_currency_currency_service_proto protoreflect.FileDescriptor

const file_currency_currency_service_proto_rawDesc = "" +
	"\n" +
	"\x1fcurrency/currency_service.proto\x12\bcurrency\x1a\x1fcurrency/currency_message.proto2\x8c\x01\n" +
	"\bCurrency\x12?\n" +
	"\n" +
	"CreateFish\x12\x17.currency.CreateFishReq\x1a\x18.currency.CreateFishResp\x12?\n" +
	"\n" +
	"DeleteFish\x12\x17.currency.DeleteFishReq\x1a\x18.currency.DeleteFishRespB\x1dZ\x1btenkhours/proto/pb/currencyb\x06proto3"

var file_currency_currency_service_proto_goTypes = []any{
	(*CreateFishReq)(nil),  // 0: currency.CreateFishReq
	(*DeleteFishReq)(nil),  // 1: currency.DeleteFishReq
	(*CreateFishResp)(nil), // 2: currency.CreateFishResp
	(*DeleteFishResp)(nil), // 3: currency.DeleteFishResp
}
var file_currency_currency_service_proto_depIdxs = []int32{
	0, // 0: currency.Currency.CreateFish:input_type -> currency.CreateFishReq
	1, // 1: currency.Currency.DeleteFish:input_type -> currency.DeleteFishReq
	2, // 2: currency.Currency.CreateFish:output_type -> currency.CreateFishResp
	3, // 3: currency.Currency.DeleteFish:output_type -> currency.DeleteFishResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_currency_currency_service_proto_init() }
func file_currency_currency_service_proto_init() {
	if File_currency_currency_service_proto != nil {
		return
	}
	file_currency_currency_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_currency_currency_service_proto_rawDesc), len(file_currency_currency_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_currency_currency_service_proto_goTypes,
		DependencyIndexes: file_currency_currency_service_proto_depIdxs,
	}.Build()
	File_currency_currency_service_proto = out.File
	file_currency_currency_service_proto_goTypes = nil
	file_currency_currency_service_proto_depIdxs = nil
}
