package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"tenkhours/services/analytic/entity"
)

// StatAnalytic is the resolver for the statAnalytic field.
func (r *queryResolver) StatAnalytic(ctx context.Context, filter *entity.StatAnalyticFilter) (map[string]interface{}, error) {
	return r.AnalyticBusiness.GetStatAnalytic(ctx, filter)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
