package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"tenkhours/services/analytic/entity"
	"time"
)

// StatAnalytic is the resolver for the statAnalytic field.
func (r *queryResolver) StatAnalytic(ctx context.Context, characterID string, startTime *time.Time, endTime *time.Time, analyticSections []entity.AnalyticSection) (map[string]interface{}, error) {
	if startTime != nil && endTime != nil && startTime.After(*endTime) {
		return nil, fmt.Errorf("start time must be before end time")
	}

	return r.AnalyticBusiness.GetStatAnalytic(ctx, characterID, startTime, endTime, analyticSections)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
