package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"tenkhours/services/notification/entity"
)

// AddToWaitlist is the resolver for the addToWaitlist field.
func (r *mutationResolver) AddToWaitlist(ctx context.Context, email string) (bool, error) {
	err := r.NotificationBusiness.AddEmailToWaitlist(ctx, email)
	if err != nil {
		fmt.Printf("Failed to add email to waitlist: %v\n", err)
		return false, err
	}

	return true, nil
}

// RegisterDeviceToken is the resolver for the RegisterDeviceToken field.
func (r *mutationResolver) RegisterDeviceToken(ctx context.Context, token string, profileID string, deviceID string, platform string) (bool, error) {
	_, err := r.NotificationBusiness.RegisterDeviceToken(ctx, profileID, token, deviceID, platform)
	if err != nil {
		fmt.Printf("Failed to register device token: %v\n", err)
		return false, err
	}

	return true, nil
}

// RemoveDeviceToken is the resolver for the RemoveDeviceToken field.
func (r *mutationResolver) RemoveDeviceToken(ctx context.Context, token string, profileID string, deviceID string) (bool, error) {
	_, err := r.NotificationBusiness.RemoveDeviceToken(ctx, profileID, token)
	if err != nil {
		fmt.Printf("Failed to remove device token: %v\n", err)
		return false, err
	}

	return true, nil
}

// CreateReminder is the resolver for the createReminder field.
func (r *mutationResolver) CreateReminder(ctx context.Context, input entity.ReminderInput) (*entity.Reminder, error) {
	createdReminder, err := r.ReminderBusiness.CreateReminder(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("failed to create reminder: %w", err)
	}

	return createdReminder, nil
}

// UpdateReminder is the resolver for the updateReminder field.
func (r *mutationResolver) UpdateReminder(ctx context.Context, id string, input entity.ReminderInput) (*entity.Reminder, error) {
	updatedReminder, err := r.ReminderBusiness.UpdateReminder(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("failed to update reminder: %w", err)
	}

	return updatedReminder, nil
}

// DeleteReminder is the resolver for the deleteReminder field.
func (r *mutationResolver) DeleteReminder(ctx context.Context, id string) (bool, error) {
	deleted, err := r.ReminderBusiness.DeleteReminder(ctx, id)
	if err != nil {
		return false, fmt.Errorf("failed to delete reminder: %w", err)
	}

	return deleted, nil
}

// GetReminders is the resolver for the getReminders field.
func (r *queryResolver) GetReminders(ctx context.Context) ([]*entity.Reminder, error) {
	reminders, err := r.ReminderBusiness.GetRemindersByProfileID(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get reminders: %w", err)
	}

	return reminders, nil
}

// GetReminder is the resolver for the getReminder field.
func (r *queryResolver) GetReminder(ctx context.Context, id string) (*entity.Reminder, error) {
	reminder, err := r.ReminderBusiness.GetReminderByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get reminder: %w", err)
	}

	return reminder, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
