package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
)

// AddToWaitlist is the resolver for the addToWaitlist field.
func (r *mutationResolver) AddToWaitlist(ctx context.Context, email string) (bool, error) {
	err := r.NotificationBusiness.AddEmailToWaitlist(ctx, email)
	if err != nil {
		fmt.Printf("Failed to add email to waitlist: %v\n", err)
		return false, err
	}

	return true, nil
}

// RegisterDeviceToken is the resolver for the RegisterDeviceToken field.
func (r *mutationResolver) RegisterDeviceToken(ctx context.Context, token string, profileID string, deviceID string, platform string) (bool, error) {
	_, err := r.NotificationBusiness.RegisterDeviceToken(ctx, profileID, token, deviceID, platform)
	if err != nil {
		fmt.Printf("Failed to register device token: %v\n", err)
		return false, err
	}

	return true, nil
}

// RemoveDeviceToken is the resolver for the RemoveDeviceToken field.
func (r *mutationResolver) RemoveDeviceToken(ctx context.Context, token string, profileID string, deviceID string) (bool, error) {
	_, err := r.NotificationBusiness.RemoveDeviceToken(ctx, profileID, token)
	if err != nil {
		fmt.Printf("Failed to remove device token: %v\n", err)
		return false, err
	}

	return true, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
