// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Character struct {
	ID string `json:"id"`
}

func (Character) IsEntity() {}

type Mutation struct {
}

type Query struct {
}

type Snapshot struct {
	ID        string     `json:"id"`
	Timestamp string     `json:"timestamp"`
	Character *Character `json:"character"`
}
