package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"tenkhours/pkg/db/timetrackingsdb"
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// CreateTimeTracking is the resolver for the createTimeTracking field.
func (r *mutationResolver) CreateTimeTracking(ctx context.Context, characterID primitive.ObjectID, customMetricID *primitive.ObjectID, startTime time.Time) (*timetrackingsdb.TimeTracking, error) {
	return r.TimeTrackingsHandler.CreateTimeTracking(ctx, characterID, customMetricID, startTime)
}

// UpdateTimeTracking is the resolver for the updateTimeTracking field.
func (r *mutationResolver) UpdateTimeTracking(ctx context.Context, id primitive.ObjectID, characterID primitive.ObjectID, customMetricID *primitive.ObjectID) (*timetrackingsdb.TimeTracking, error) {
	return r.TimeTrackingsHandler.UpdateTimeTracking(ctx, id, characterID, customMetricID)
}

// CurrentTimeTracking is the resolver for the currentTimeTracking field.
func (r *queryResolver) CurrentTimeTracking(ctx context.Context, characterID primitive.ObjectID) (*timetrackingsdb.TimeTracking, error) {
	return r.TimeTrackingsHandler.GetCurrentTimeTracking(ctx, characterID)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
