// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"tenkhours/services/core/entity"
)

type AppSettings struct {
	MinDurationTime        int `json:"minDurationTime"`
	MaxDurationTime        int `json:"maxDurationTime"`
	LimitedCharacterNumber int `json:"limitedCharacterNumber"`
	LimitedCategoryNumber  int `json:"limitedCategoryNumber"`
	LimitedMetricNumber    int `json:"limitedMetricNumber"`
}

type Fish struct {
	ProfileID string `json:"profileID"`
}

func (Fish) IsEntity() {}

type GoalMetric struct {
	ID          string                 `json:"id"`
	CategoryID  *string                `json:"categoryID,omitempty"`
	Name        string                 `json:"name"`
	Value       float64                `json:"value"`
	Unit        string                 `json:"unit"`
	Condition   entity.MetricCondition `json:"condition"`
	TargetValue *float64               `json:"targetValue,omitempty"`
	RangeValue  *entity.Range          `json:"rangeValue,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
