// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AppSettings struct {
	MinDurationTime       int `json:"minDurationTime"`
	MaxDurationTime       int `json:"maxDurationTime"`
	LimitedMetricNumber   int `json:"limitedMetricNumber"`
	LimitedPropertyNumber int `json:"limitedPropertyNumber"`
}

type Fish struct {
	ProfileID string `json:"profileID"`
}

func (Fish) IsEntity() {}

type Mutation struct {
}

type Query struct {
}
