// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AppSettings struct {
	MinDurationTime        int `json:"minDurationTime"`
	MaxDurationTime        int `json:"maxDurationTime"`
	LimitedCharacterNumber int `json:"limitedCharacterNumber"`
	LimitedCategoryNumber  int `json:"limitedCategoryNumber"`
	LimitedMetricNumber    int `json:"limitedMetricNumber"`
}

type Fish struct {
	ProfileID string `json:"profileID"`
}

func (Fish) IsEntity() {}

type Mutation struct {
}

type Query struct {
}
