package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"tenkhours/services/currency/entity"
)

// GetDailyReward is the resolver for the getDailyReward field.
func (r *mutationResolver) GetDailyReward(ctx context.Context) (*entity.Reward, error) {
	return r.RewardBusiness.ClaimDailyReward(ctx)
}

// Reward is the resolver for the reward field.
func (r *queryResolver) Reward(ctx context.Context) (*entity.Reward, error) {
	return r.RewardBusiness.GetRewardByProfileID(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
