package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"tenkhours/services/core/entity"
	"tenkhours/services/core/transport/graph/model"
)

// Vision is the resolver for the vision field.
func (r *characterInputResolver) Vision(ctx context.Context, obj *entity.CharacterInput, data *model.VisionInput) error {
	panic(fmt.Errorf("not implemented: Vision - vision"))
}

// CharacterInput returns CharacterInputResolver implementation.
func (r *Resolver) CharacterInput() CharacterInputResolver { return &characterInputResolver{r} }

type characterInputResolver struct{ *Resolver }
