package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"tenkhours/services/core/entity"
)

// Time is the resolver for the time field.
func (r *characterResolver) Time(ctx context.Context, obj *entity.Character) (int, error) {
	return r.TimeTrackingRepo.GetTotalTimeByCharacterID(ctx, obj.ID)
}

// Character returns CharacterResolver implementation.
func (r *Resolver) Character() CharacterResolver { return &characterResolver{r} }

type characterResolver struct{ *Resolver }
