package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"tenkhours/services/core/entity"
)

// Metric is the resolver for the metric field.
func (r *goalMetricResolver) Metric(ctx context.Context, obj *entity.GoalMetric) (*entity.Metric, error) {
	return r.MetricRepo.FindByID(ctx, obj.ID)
}

// GoalMetric returns GoalMetricResolver implementation.
func (r *Resolver) GoalMetric() GoalMetricResolver { return &goalMetricResolver{r} }

type goalMetricResolver struct{ *Resolver }
