package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	gql "tenkhours/pkg/graphql"
	"tenkhours/services/core/entity"

	"github.com/samber/lo"
)

// CategoryID is the resolver for the categoryID field.
func (r *habitResolver) CategoryID(ctx context.Context, obj *entity.Habit) (*string, error) {
	if obj.CategoryID == nil {
		obj.CategoryID = lo.ToPtr(gql.UnassignedID)
	}
	return obj.CategoryID, nil
}

// Category is the resolver for the category field.
func (r *habitResolver) Category(ctx context.Context, obj *entity.Habit) (*entity.Category, error) {
	if obj.CategoryID == nil || *obj.CategoryID == gql.UnassignedID {
		return nil, nil
	}
	return r.CategoryRepo.FindByID(ctx, *obj.CategoryID)
}

// Reset is the resolver for the reset field.
func (r *habitResolver) Reset(ctx context.Context, obj *entity.Habit) (entity.HabitReset, error) {
	panic(fmt.Errorf("not implemented: Reset - reset"))
}

// Keep is the resolver for the _keep field.
func (r *habitFilterResolver) Keep(ctx context.Context, obj *entity.HabitFilter, data *bool) error {
	panic(fmt.Errorf("not implemented: Keep - _keep"))
}

// Reset is the resolver for the reset field.
func (r *habitInputResolver) Reset(ctx context.Context, obj *entity.HabitInput, data entity.HabitReset) error {
	panic(fmt.Errorf("not implemented: Reset - reset"))
}

// Keep is the resolver for the _keep field.
func (r *habitOrderByResolver) Keep(ctx context.Context, obj *entity.HabitOrderBy, data *bool) error {
	panic(fmt.Errorf("not implemented: Keep - _keep"))
}

// Habit returns HabitResolver implementation.
func (r *Resolver) Habit() HabitResolver { return &habitResolver{r} }

// HabitFilter returns HabitFilterResolver implementation.
func (r *Resolver) HabitFilter() HabitFilterResolver { return &habitFilterResolver{r} }

// HabitInput returns HabitInputResolver implementation.
func (r *Resolver) HabitInput() HabitInputResolver { return &habitInputResolver{r} }

// HabitOrderBy returns HabitOrderByResolver implementation.
func (r *Resolver) HabitOrderBy() HabitOrderByResolver { return &habitOrderByResolver{r} }

type habitResolver struct{ *Resolver }
type habitFilterResolver struct{ *Resolver }
type habitInputResolver struct{ *Resolver }
type habitOrderByResolver struct{ *Resolver }
