package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	gql "tenkhours/pkg/graphql"
	"tenkhours/services/core/entity"

	"github.com/samber/lo"
)

// CategoryID is the resolver for the categoryID field.
func (r *habitResolver) CategoryID(ctx context.Context, obj *entity.Habit) (*string, error) {
	if obj.CategoryID == nil {
		obj.CategoryID = lo.ToPtr(gql.UnassignedID)
	}
	return obj.CategoryID, nil
}

// Category is the resolver for the category field.
func (r *habitResolver) Category(ctx context.Context, obj *entity.Habit) (*entity.Category, error) {
	if obj.CategoryID == nil || *obj.CategoryID == gql.UnassignedID {
		return nil, nil
	}
	return r.CategoryRepo.FindByID(ctx, *obj.CategoryID)
}

// Habit returns HabitResolver implementation.
func (r *Resolver) Habit() HabitResolver { return &habitResolver{r} }

type habitResolver struct{ *Resolver }
