package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"tenkhours/pkg/graphql"
	"tenkhours/services/core/entity"

	"github.com/samber/lo"
)

// CategoryID is the resolver for the categoryID field.
func (r *metricResolver) CategoryID(ctx context.Context, obj *entity.Metric) (*string, error) {
	if obj.CategoryID == nil {
		obj.CategoryID = lo.ToPtr(graphql.UnassignedID)
	}
	return obj.CategoryID, nil
}

// Category is the resolver for the category field.
func (r *metricResolver) Category(ctx context.Context, obj *entity.Metric) (*entity.Category, error) {
	if obj.CategoryID == nil || *obj.CategoryID == graphql.UnassignedID {
		return nil, nil
	}
	return r.CategoryRepo.FindByID(ctx, *obj.CategoryID)
}

// Metric returns MetricResolver implementation.
func (r *Resolver) Metric() MetricResolver { return &metricResolver{r} }

type metricResolver struct{ *Resolver }
