package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"tenkhours/services/core/entity"
)

// Keep is the resolver for the _keep field.
func (r *reminderFilterResolver) Keep(ctx context.Context, obj *entity.ReminderFilter, data *bool) error {
	panic(fmt.Errorf("not implemented: Keep - _keep"))
}

// Keep is the resolver for the _keep field.
func (r *reminderOrderByResolver) Keep(ctx context.Context, obj *entity.ReminderOrderBy, data *bool) error {
	panic(fmt.Errorf("not implemented: Keep - _keep"))
}

// ReminderFilter returns ReminderFilterResolver implementation.
func (r *Resolver) ReminderFilter() ReminderFilterResolver { return &reminderFilterResolver{r} }

// ReminderOrderBy returns ReminderOrderByResolver implementation.
func (r *Resolver) ReminderOrderBy() ReminderOrderByResolver { return &reminderOrderByResolver{r} }

type reminderFilterResolver struct{ *Resolver }
type reminderOrderByResolver struct{ *Resolver }
