package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"tenkhours/pkg/utils"
	"tenkhours/services/core/entity"
	"tenkhours/services/core/transport/graph/model"
	"tenkhours/services/core/transport/graph/validations"
)

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input entity.ProfileInput) (*entity.Profile, error) {
	// Validate the input
	if err := validations.ValidateProfileInput(input); err != nil {
		return nil, err
	}

	return r.ProfileBusiness.UpdateProfile(ctx, input)
}

// DeleteProfile is the resolver for the deleteProfile field.
func (r *mutationResolver) DeleteProfile(ctx context.Context) (*entity.Profile, error) {
	return r.ProfileBusiness.DeleteProfile(ctx)
}

// UpsertCharacter is the resolver for the upsertCharacter field.
func (r *mutationResolver) UpsertCharacter(ctx context.Context, input entity.CharacterInput) (*entity.Character, error) {
	// Validate the input
	if err := validations.ValidateCharacterInput(input); err != nil {
		return nil, err
	}

	return r.CharacterBusiness.UpsertCharacter(ctx, input)
}

// DeleteCharacter is the resolver for the deleteCharacter field.
func (r *mutationResolver) DeleteCharacter(ctx context.Context, id string) (*entity.Character, error) {
	return r.CharacterBusiness.DeleteCharacter(ctx, id)
}

// UpsertGoal is the resolver for the upsertGoal field.
func (r *mutationResolver) UpsertGoal(ctx context.Context, characterID string, input entity.GoalInput) (*entity.Goal, error) {
	// Validate the input
	if err := validations.ValidateGoalInput(input); err != nil {
		return nil, err
	}

	return r.GoalsBusiness.UpsertGoal(ctx, characterID, input)
}

// Characters is the resolver for the characters field.
func (r *queryResolver) Characters(ctx context.Context) ([]entity.Character, error) {
	return r.CharacterBusiness.GetCharactersByProfileID(ctx)
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context) (*entity.Profile, error) {
	return r.ProfileBusiness.GetProfile(ctx)
}

// AppSettings is the resolver for the appSettings field.
func (r *queryResolver) AppSettings(ctx context.Context) (*model.AppSettings, error) {
	return &model.AppSettings{
		MinDurationTime:        utils.MinDurationTime,
		MaxDurationTime:        utils.MaxDurationTime,
		LimitedCharacterNumber: utils.LimitedCharacterNumber,
		LimitedCategoryNumber:  utils.LimitedCategoryNumber,
		LimitedMetricNumber:    utils.LimitedMetricNumber,
	}, nil
}

// Goals is the resolver for the goals field.
func (r *queryResolver) Goals(ctx context.Context, characterID string, status *entity.GoalStatusFilter) ([]entity.Goal, error) {
	return r.GoalsBusiness.GetGoals(ctx, characterID, status)
}

// Templates is the resolver for the templates field.
func (r *queryResolver) Templates(ctx context.Context) ([]entity.Template, error) {
	return r.TemplateBusiness.GetTemplates(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
