package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	gql "tenkhours/pkg/graphql"
	"tenkhours/services/core/entity"

	"github.com/samber/lo"
)

// CategoryID is the resolver for the categoryID field.
func (r *taskResolver) CategoryID(ctx context.Context, obj *entity.Task) (*string, error) {
	if obj.CategoryID == nil {
		obj.CategoryID = lo.ToPtr(gql.UnassignedID)
	}
	return obj.CategoryID, nil
}

// Task returns TaskResolver implementation.
func (r *Resolver) Task() TaskResolver { return &taskResolver{r} }

type taskResolver struct{ *Resolver }
