package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"tenkhours/services/core/entity"
)

// Keep is the resolver for the _keep field.
func (r *taskSessionOrderByResolver) Keep(ctx context.Context, obj *entity.TaskSessionOrderBy, data *bool) error {
	panic(fmt.Errorf("not implemented: Keep - _keep"))
}

// TaskSessionOrderBy returns TaskSessionOrderByResolver implementation.
func (r *Resolver) TaskSessionOrderBy() TaskSessionOrderByResolver {
	return &taskSessionOrderByResolver{r}
}

type taskSessionOrderByResolver struct{ *Resolver }
