package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"tenkhours/services/core/entity"
)

// Topic is the resolver for the topic field.
func (r *templateResolver) Topic(ctx context.Context, obj *entity.Template) (*entity.TemplateTopic, error) {
	panic(fmt.Errorf("not implemented: Topic - topic"))
}

// Template returns TemplateResolver implementation.
func (r *Resolver) Template() TemplateResolver { return &templateResolver{r} }

type templateResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *templateResolver) Category(ctx context.Context, obj *entity.Template) (*entity.TemplateTopic, error) {
	return r.TemplateBusiness.GetTemplateCategory(ctx, obj.TopicID)
}
