package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"tenkhours/services/core/entity"
)

// Category is the resolver for the category field.
func (r *templateResolver) Category(ctx context.Context, obj *entity.Template) (*entity.TemplateCategory, error) {
	return r.TemplateBusiness.GetTemplateCategory(ctx, obj.CategoryID)
}

// Template returns TemplateResolver implementation.
func (r *Resolver) Template() TemplateResolver { return &templateResolver{r} }

type templateResolver struct{ *Resolver }
