[request_definition]
r = sub_type, obj_type, sub, obj, act

[policy_definition]
p = sub_type, obj_type, sub_rule, obj_rule, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub_type == p.sub_type \
    && r.obj_type == p.obj_type  \
    && eval(p.sub_rule) \
    && eval(p.obj_rule) \
    && r.act == p.act