// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v3.21.12
// source: currency.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CatchFishResp_FishType int32

const (
	CatchFishResp_None   CatchFishResp_FishType = 0
	CatchFishResp_Normal CatchFishResp_FishType = 1
	CatchFishResp_Gold   CatchFishResp_FishType = 2
)

// Enum value maps for CatchFishResp_FishType.
var (
	CatchFishResp_FishType_name = map[int32]string{
		0: "None",
		1: "Normal",
		2: "Gold",
	}
	CatchFishResp_FishType_value = map[string]int32{
		"None":   0,
		"Normal": 1,
		"Gold":   2,
	}
)

func (x CatchFishResp_FishType) Enum() *CatchFishResp_FishType {
	p := new(CatchFishResp_FishType)
	*p = x
	return p
}

func (x CatchFishResp_FishType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CatchFishResp_FishType) Descriptor() protoreflect.EnumDescriptor {
	return file_currency_proto_enumTypes[0].Descriptor()
}

func (CatchFishResp_FishType) Type() protoreflect.EnumType {
	return &file_currency_proto_enumTypes[0]
}

func (x CatchFishResp_FishType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CatchFishResp_FishType.Descriptor instead.
func (CatchFishResp_FishType) EnumDescriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{5, 0}
}

type CreateFishReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileID     string                 `protobuf:"bytes,1,opt,name=profileID,proto3" json:"profileID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFishReq) Reset() {
	*x = CreateFishReq{}
	mi := &file_currency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFishReq) ProtoMessage() {}

func (x *CreateFishReq) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFishReq.ProtoReflect.Descriptor instead.
func (*CreateFishReq) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFishReq) GetProfileID() string {
	if x != nil {
		return x.ProfileID
	}
	return ""
}

type CreateFishResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFishResp) Reset() {
	*x = CreateFishResp{}
	mi := &file_currency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFishResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFishResp) ProtoMessage() {}

func (x *CreateFishResp) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFishResp.ProtoReflect.Descriptor instead.
func (*CreateFishResp) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFishResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateFishReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileID     string                 `protobuf:"bytes,1,opt,name=profileID,proto3" json:"profileID,omitempty"`
	Gold          int32                  `protobuf:"varint,2,opt,name=gold,proto3" json:"gold,omitempty"`
	Normal        int32                  `protobuf:"varint,3,opt,name=normal,proto3" json:"normal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFishReq) Reset() {
	*x = UpdateFishReq{}
	mi := &file_currency_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFishReq) ProtoMessage() {}

func (x *UpdateFishReq) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFishReq.ProtoReflect.Descriptor instead.
func (*UpdateFishReq) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateFishReq) GetProfileID() string {
	if x != nil {
		return x.ProfileID
	}
	return ""
}

func (x *UpdateFishReq) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *UpdateFishReq) GetNormal() int32 {
	if x != nil {
		return x.Normal
	}
	return 0
}

type UpdateFishResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FishID        string                 `protobuf:"bytes,1,opt,name=fishID,proto3" json:"fishID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFishResp) Reset() {
	*x = UpdateFishResp{}
	mi := &file_currency_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFishResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFishResp) ProtoMessage() {}

func (x *UpdateFishResp) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFishResp.ProtoReflect.Descriptor instead.
func (*UpdateFishResp) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateFishResp) GetFishID() string {
	if x != nil {
		return x.FishID
	}
	return ""
}

type CatchFishReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatchFishReq) Reset() {
	*x = CatchFishReq{}
	mi := &file_currency_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchFishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchFishReq) ProtoMessage() {}

func (x *CatchFishReq) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatchFishReq.ProtoReflect.Descriptor instead.
func (*CatchFishReq) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{4}
}

type CatchFishResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FishType      CatchFishResp_FishType `protobuf:"varint,1,opt,name=fishType,proto3,enum=pb.CatchFishResp_FishType" json:"fishType,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CatchFishResp) Reset() {
	*x = CatchFishResp{}
	mi := &file_currency_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchFishResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchFishResp) ProtoMessage() {}

func (x *CatchFishResp) ProtoReflect() protoreflect.Message {
	mi := &file_currency_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatchFishResp.ProtoReflect.Descriptor instead.
func (*CatchFishResp) Descriptor() ([]byte, []int) {
	return file_currency_proto_rawDescGZIP(), []int{5}
}

func (x *CatchFishResp) GetFishType() CatchFishResp_FishType {
	if x != nil {
		return x.FishType
	}
	return CatchFishResp_None
}

func (x *CatchFishResp) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_currency_proto protoreflect.FileDescriptor

var file_currency_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x2d, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69,
	0x73, 0x68, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x49, 0x44, 0x22, 0x2a, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x73,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22,
	0x59, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x67, 0x6f,
	0x6c, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x22, 0x28, 0x0a, 0x0e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x69, 0x73, 0x68, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69,
	0x73, 0x68, 0x49, 0x44, 0x22, 0x0e, 0x0a, 0x0c, 0x43, 0x61, 0x74, 0x63, 0x68, 0x46, 0x69, 0x73,
	0x68, 0x52, 0x65, 0x71, 0x22, 0x8b, 0x01, 0x0a, 0x0d, 0x43, 0x61, 0x74, 0x63, 0x68, 0x46, 0x69,
	0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x08, 0x66, 0x69, 0x73, 0x68, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61,
	0x74, 0x63, 0x68, 0x46, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x46, 0x69, 0x73, 0x68,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x66, 0x69, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x08, 0x46, 0x69, 0x73, 0x68, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x6f, 0x6c, 0x64,
	0x10, 0x02, 0x32, 0xac, 0x01, 0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12,
	0x35, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x73, 0x68, 0x12, 0x11, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71,
	0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x73, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x46, 0x69, 0x73, 0x68, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x46, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x46, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x32, 0x0a,
	0x09, 0x43, 0x61, 0x74, 0x63, 0x68, 0x46, 0x69, 0x73, 0x68, 0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x61, 0x74, 0x63, 0x68, 0x46, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x61, 0x74, 0x63, 0x68, 0x46, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_currency_proto_rawDescOnce sync.Once
	file_currency_proto_rawDescData = file_currency_proto_rawDesc
)

func file_currency_proto_rawDescGZIP() []byte {
	file_currency_proto_rawDescOnce.Do(func() {
		file_currency_proto_rawDescData = protoimpl.X.CompressGZIP(file_currency_proto_rawDescData)
	})
	return file_currency_proto_rawDescData
}

var file_currency_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_currency_proto_goTypes = []any{
	(CatchFishResp_FishType)(0), // 0: pb.CatchFishResp.FishType
	(*CreateFishReq)(nil),       // 1: pb.CreateFishReq
	(*CreateFishResp)(nil),      // 2: pb.CreateFishResp
	(*UpdateFishReq)(nil),       // 3: pb.UpdateFishReq
	(*UpdateFishResp)(nil),      // 4: pb.UpdateFishResp
	(*CatchFishReq)(nil),        // 5: pb.CatchFishReq
	(*CatchFishResp)(nil),       // 6: pb.CatchFishResp
}
var file_currency_proto_depIdxs = []int32{
	0, // 0: pb.CatchFishResp.fishType:type_name -> pb.CatchFishResp.FishType
	1, // 1: pb.Currency.CreateFish:input_type -> pb.CreateFishReq
	3, // 2: pb.Currency.UpdateFish:input_type -> pb.UpdateFishReq
	5, // 3: pb.Currency.CatchFish:input_type -> pb.CatchFishReq
	2, // 4: pb.Currency.CreateFish:output_type -> pb.CreateFishResp
	4, // 5: pb.Currency.UpdateFish:output_type -> pb.UpdateFishResp
	6, // 6: pb.Currency.CatchFish:output_type -> pb.CatchFishResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_currency_proto_init() }
func file_currency_proto_init() {
	if File_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_currency_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_currency_proto_goTypes,
		DependencyIndexes: file_currency_proto_depIdxs,
		EnumInfos:         file_currency_proto_enumTypes,
		MessageInfos:      file_currency_proto_msgTypes,
	}.Build()
	File_currency_proto = out.File
	file_currency_proto_rawDesc = nil
	file_currency_proto_goTypes = nil
	file_currency_proto_depIdxs = nil
}
