// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: notification/notification_message.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendPushNotificationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPushNotificationReq) Reset() {
	*x = SendPushNotificationReq{}
	mi := &file_notification_notification_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPushNotificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPushNotificationReq) ProtoMessage() {}

func (x *SendPushNotificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPushNotificationReq.ProtoReflect.Descriptor instead.
func (*SendPushNotificationReq) Descriptor() ([]byte, []int) {
	return file_notification_notification_message_proto_rawDescGZIP(), []int{0}
}

func (x *SendPushNotificationReq) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *SendPushNotificationReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SendPushNotificationReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendPushNotificationReq) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type SendPushNotificationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPushNotificationResp) Reset() {
	*x = SendPushNotificationResp{}
	mi := &file_notification_notification_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPushNotificationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPushNotificationResp) ProtoMessage() {}

func (x *SendPushNotificationResp) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPushNotificationResp.ProtoReflect.Descriptor instead.
func (*SendPushNotificationResp) Descriptor() ([]byte, []int) {
	return file_notification_notification_message_proto_rawDescGZIP(), []int{1}
}

func (x *SendPushNotificationResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_notification_notification_message_proto protoreflect.FileDescriptor

const file_notification_notification_message_proto_rawDesc = "" +
	"\n" +
	"'notification/notification_message.proto\x12\fnotification\"\x7f\n" +
	"\x17SendPushNotificationReq\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\"4\n" +
	"\x18SendPushNotificationResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB!Z\x1ftenkhours/proto/pb/notificationb\x06proto3"

var (
	file_notification_notification_message_proto_rawDescOnce sync.Once
	file_notification_notification_message_proto_rawDescData []byte
)

func file_notification_notification_message_proto_rawDescGZIP() []byte {
	file_notification_notification_message_proto_rawDescOnce.Do(func() {
		file_notification_notification_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_notification_message_proto_rawDesc), len(file_notification_notification_message_proto_rawDesc)))
	})
	return file_notification_notification_message_proto_rawDescData
}

var file_notification_notification_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notification_notification_message_proto_goTypes = []any{
	(*SendPushNotificationReq)(nil),  // 0: notification.SendPushNotificationReq
	(*SendPushNotificationResp)(nil), // 1: notification.SendPushNotificationResp
}
var file_notification_notification_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notification_notification_message_proto_init() }
func file_notification_notification_message_proto_init() {
	if File_notification_notification_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_notification_message_proto_rawDesc), len(file_notification_notification_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notification_notification_message_proto_goTypes,
		DependencyIndexes: file_notification_notification_message_proto_depIdxs,
		MessageInfos:      file_notification_notification_message_proto_msgTypes,
	}.Build()
	File_notification_notification_message_proto = out.File
	file_notification_notification_message_proto_goTypes = nil
	file_notification_notification_message_proto_depIdxs = nil
}
