filebeat.inputs:
- type: container
  paths:
  - "/var/lib/docker/containers/*/*.log"
  processors:
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

output.elasticsearch:
  hosts: [ "https://es01:9200" ]
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"
  ssl.verification_mode: "none"
