package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"tenkhours/services/currency/repo"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// FindFishByProfileID is the resolver for the findFishByProfileID field.
func (r *entityResolver) FindFishByProfileID(ctx context.Context, profileID primitive.ObjectID) (*repo.Fish, error) {
	return r.FishBusiness.FishRepo.GetFishByProfileID(profileID)
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
