package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"tenkhours/services/currency/repo"
)

// ID is the resolver for the id field.
func (r *fishResolver) ID(ctx context.Context, obj *repo.Fish) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// ProfileID is the resolver for the profileID field.
func (r *fishResolver) ProfileID(ctx context.Context, obj *repo.Fish) (string, error) {
	panic(fmt.Errorf("not implemented: ProfileID - profileID"))
}

// Fish returns FishResolver implementation.
func (r *Resolver) Fish() FishResolver { return &fishResolver{r} }

type fishResolver struct{ *Resolver }
