package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"tenkhours/services/currency/graph/model"
	"tenkhours/services/currency/repo"
)

// UnlockMetrics is the resolver for the unlockMetrics field.
func (r *mutationResolver) UnlockMetrics(ctx context.Context, fishType model.FishType, characterID string) (bool, error) {
	return r.FishBusiness.UnlockMetrics(ctx, fishType, characterID)
}

// BuySnapshots is the resolver for the buySnapshots field.
func (r *mutationResolver) BuySnapshots(ctx context.Context, fishType model.FishType) (bool, error) {
	// No need for profileID as argument; get it from context
	return r.FishBusiness.BuySnapshots(ctx, fishType)
}

// OnBoardCharacters is the resolver for the onBoardCharacters field.
func (r *mutationResolver) OnBoardCharacters(ctx context.Context, fishType model.FishType) (bool, error) {
	return r.FishBusiness.UnclockNewCharacters(ctx, fishType)
}

// GetFishByProfileID is the resolver for the getFishByProfileId field.
func (r *queryResolver) GetFishByProfileID(ctx context.Context) (*repo.Fish, error) {
	return r.FishBusiness.GetFishByProfileID(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
