package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"
	"tenkhours/services/currency/graph/model"
	"tenkhours/services/currency/graph/validations"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// CreateFish is the resolver for the createFish field.
func (r *mutationResolver) CreateFish(ctx context.Context, input model.FishInput) (*model.Fish, error) {
	//validate fish input
	if err := validations.ValidateFishInput(input); err != nil {
		return nil, err
	}

	return r.FishBusiness.CreateFish(ctx, input)
}

// UpdateFish is the resolver for the updateFish field.
func (r *mutationResolver) UpdateFish(ctx context.Context, id primitive.ObjectID, input model.FishInput) (*model.Fish, error) {
	//validate fish input
	if err := validations.ValidateFishInput(input); err != nil {
		return nil, err
	}

	return r.FishBusiness.UpdateFish(ctx, id, input)
}

// CatchFish is the resolver for the catchFish field.
func (r *mutationResolver) CatchFish(ctx context.Context, id primitive.ObjectID) (*model.Fish, error) {
	return r.FishBusiness.CatchFish(ctx, id)
}

// CreateCod is the resolver for the createCod field.
func (r *mutationResolver) CreateCod(ctx context.Context, input model.CodInput) (*model.Cod, error) {
	panic(fmt.Errorf("not implemented: CreateCod - createCod"))
}

// UpdateCod is the resolver for the updateCod field.
func (r *mutationResolver) UpdateCod(ctx context.Context, input model.CodInput) (*model.Cod, error) {
	panic(fmt.Errorf("not implemented: UpdateCod - updateCod"))
}

// UnlockMetricsWithNormalFish is the resolver for the unlockMetricsWithNormalFish field.
func (r *mutationResolver) UnlockMetricsWithNormalFish(ctx context.Context, id primitive.ObjectID, characterID primitive.ObjectID) (bool, error) {
	return r.FishBusiness.UnlockMetricsWithNormalFish(ctx, id, characterID)
}

// BuySnapshotsWithNormalFish is the resolver for the buySnapshotsWithNormalFish field.
func (r *mutationResolver) BuySnapshotsWithNormalFish(ctx context.Context, id primitive.ObjectID) (bool, error) {
	return r.FishBusiness.BuySnapshotsWithNormalFish(ctx, id)
}

// UnlockMetricsWithGoldFish is the resolver for the unlockMetricsWithGoldFish field.
func (r *mutationResolver) UnlockMetricsWithGoldFish(ctx context.Context, id primitive.ObjectID, characterID primitive.ObjectID) (bool, error) {
	return r.FishBusiness.UnlockMetricsWithGoldFish(ctx, id, characterID)
}

// BuySnapshotsWithGoldFish is the resolver for the buySnapshotsWithGoldFish field.
func (r *mutationResolver) BuySnapshotsWithGoldFish(ctx context.Context, id primitive.ObjectID) (bool, error) {
	return r.FishBusiness.BuySnapshotsWithGoldFish(ctx, id)
}

// GetFishByProfileID is the resolver for the getFishByProfileId field.
func (r *queryResolver) GetFishByProfileID(ctx context.Context, fishType string) (*model.Fish, error) {
	return r.Resolver.FishBusiness.GetFishByProfileID(ctx, fishType)
}

// GetCodByProfileID is the resolver for the getCodByProfileId field.
func (r *queryResolver) GetCodByProfileID(ctx context.Context) (*model.Cod, error) {
	panic(fmt.Errorf("not implemented: GetCodByProfileID - getCodByProfileId"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
