package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"tenkhours/services/currency/graph/model"
	"tenkhours/services/currency/repo"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// BuyMetrics is the resolver for the buyMetrics field.
func (r *mutationResolver) BuyMetrics(ctx context.Context, fishType model.FishType, characterID primitive.ObjectID) (bool, error) {
	return r.FishBusiness.BuyMetrics(ctx, fishType, characterID)
}

// BuySnapshots is the resolver for the buySnapshots field.
func (r *mutationResolver) BuySnapshots(ctx context.Context, fishType model.FishType) (bool, error) {
	return r.FishBusiness.BuySnapshots(ctx, fishType)
}

// BuyCharacters is the resolver for the buyCharacters field.
func (r *mutationResolver) BuyCharacters(ctx context.Context, fishType model.FishType) (bool, error) {
	return r.FishBusiness.BuyCharacters(ctx, fishType)
}

// Fish is the resolver for the fish field.
func (r *queryResolver) Fish(ctx context.Context) (*repo.Fish, error) {
	return r.FishBusiness.GetFishByProfileID(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
