package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"tenkhours/pkg/db/coredb"
)

// FindCharacterByID is the resolver for the findCharacterByID field.
func (r *entityResolver) FindCharacterByID(ctx context.Context, id string) (*coredb.Character, error) {
	return r.CharactersHandler.GetCharacterByID(ctx, id)
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
