package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"tenkhours/pkg/db/coredb"
	"time"
)

// ID is the resolver for the id field.
func (r *profileResolver) ID(ctx context.Context, obj *coredb.Profile) (string, error) {
	return obj.ID.Hex(), nil
}

// CurrentCharacterID is the resolver for the currentCharacterID field.
func (r *profileResolver) CurrentCharacterID(ctx context.Context, obj *coredb.Profile) (*string, error) {
	if obj.ID.IsZero() {
		return nil, nil
	}

	id := obj.ID.Hex()
	return &id, nil
}

// Characters is the resolver for the characters field.
func (r *profileResolver) Characters(ctx context.Context, obj *coredb.Profile) ([]coredb.Character, error) {
	return r.CharactersHandler.GetCharactersByProfileID(ctx)
}

// CreatedAt is the resolver for the createdAt field.
func (r *profileResolver) CreatedAt(ctx context.Context, obj *coredb.Profile) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *profileResolver) UpdatedAt(ctx context.Context, obj *coredb.Profile) (string, error) {
	return obj.UpdatedAt.Format(time.RFC3339), nil
}

// Profile returns ProfileResolver implementation.
func (r *Resolver) Profile() ProfileResolver { return &profileResolver{r} }

type profileResolver struct{ *Resolver }
