package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"tenkhours/pkg/db/coredb"
	"tenkhours/services/core_v2/graph/model"
)

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.ProfileInput) (*coredb.Profile, error) {
	return r.ProfilesHandler.UpdateProfile(ctx, input)
}

// CreateCharacter is the resolver for the createCharacter field.
func (r *mutationResolver) CreateCharacter(ctx context.Context, input model.CharacterInput) (*coredb.Character, error) {
	return r.CharactersHandler.CreateCharacter(ctx, input)
}

// UpdateCharacter is the resolver for the updateCharacter field.
func (r *mutationResolver) UpdateCharacter(ctx context.Context, id string, input model.CharacterInput) (*coredb.Character, error) {
	return r.CharactersHandler.UpdateCharacter(ctx, id, input)
}

// DeleteCharacter is the resolver for the deleteCharacter field.
func (r *mutationResolver) DeleteCharacter(ctx context.Context, id string) (*coredb.Character, error) {
	return r.CharactersHandler.DeleteCharacter(ctx, id)
}

// ResetCharacter is the resolver for the resetCharacter field.
func (r *mutationResolver) ResetCharacter(ctx context.Context, id string) (*coredb.Character, error) {
	return r.CharactersHandler.ResetCharacter(ctx, id)
}

// CreateCustomMetric is the resolver for the createCustomMetric field.
func (r *mutationResolver) CreateCustomMetric(ctx context.Context, characterID string, input model.CustomMetricInput) (*coredb.CustomMetric, error) {
	return r.CharactersHandler.CreateCustomMetric(ctx, characterID, input)
}

// UpdateCustomMetric is the resolver for the updateCustomMetric field.
func (r *mutationResolver) UpdateCustomMetric(ctx context.Context, id string, characterID string, input model.CustomMetricInput) (*coredb.CustomMetric, error) {
	return r.CharactersHandler.UpdateCustomMetric(ctx, id, characterID, input)
}

// ResetCustomMetric is the resolver for the resetCustomMetric field.
func (r *mutationResolver) ResetCustomMetric(ctx context.Context, id string, characterID string) (*coredb.CustomMetric, error) {
	return r.CharactersHandler.ResetCustomMetric(ctx, id, characterID)
}

// DeleteCustomMetric is the resolver for the deleteCustomMetric field.
func (r *mutationResolver) DeleteCustomMetric(ctx context.Context, id string, characterID string) (*coredb.CustomMetric, error) {
	return r.CharactersHandler.DeleteCustomMetric(ctx, id, characterID)
}

// CreateMetricProperty is the resolver for the createMetricProperty field.
func (r *mutationResolver) CreateMetricProperty(ctx context.Context, characterID string, metricID string, input model.MetricPropertyInput) (*coredb.MetricProperty, error) {
	return r.CharactersHandler.CreateMetricProperty(ctx, characterID, metricID, input)
}

// UpdateMetricProperty is the resolver for the updateMetricProperty field.
func (r *mutationResolver) UpdateMetricProperty(ctx context.Context, id string, characterID string, metricID string, input model.MetricPropertyInput) (*coredb.MetricProperty, error) {
	return r.CharactersHandler.UpdateMetricProperty(ctx, id, characterID, metricID, input)
}

// DeleteMetricProperty is the resolver for the deleteMetricProperty field.
func (r *mutationResolver) DeleteMetricProperty(ctx context.Context, id string, characterID string, metricID string) (*coredb.MetricProperty, error) {
	return r.CharactersHandler.DeleteMetricProperty(ctx, id, characterID, metricID)
}

// Characters is the resolver for the characters field.
func (r *queryResolver) Characters(ctx context.Context) ([]coredb.Character, error) {
	return r.CharactersHandler.GetCharactersByProfileID(ctx)
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context) (*coredb.Profile, error) {
	return r.ProfilesHandler.GetProfileByToken(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
