// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Token struct {
	ID        string `json:"id"`
	DeviceID  string `json:"deviceID"`
	Platform  string `json:"platform"`
	CreatedAt string `json:"createdAt"`
	Token     string `json:"token"`
}

type DevicesToken struct {
	ID        string   `json:"id"`
	ProfileID string   `json:"profileID"`
	Tokens    []*Token `json:"tokens"`
}
