// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: core/category_message.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CharacterId   string                 `protobuf:"bytes,4,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Style         *CategoryStyle         `protobuf:"bytes,7,opt,name=style,proto3" json:"style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_core_category_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_core_category_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_core_category_message_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Category) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Category) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Category) GetStyle() *CategoryStyle {
	if x != nil {
		return x.Style
	}
	return nil
}

type CategoryStyle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         string                 `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	Icon          string                 `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryStyle) Reset() {
	*x = CategoryStyle{}
	mi := &file_core_category_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryStyle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryStyle) ProtoMessage() {}

func (x *CategoryStyle) ProtoReflect() protoreflect.Message {
	mi := &file_core_category_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryStyle.ProtoReflect.Descriptor instead.
func (*CategoryStyle) Descriptor() ([]byte, []int) {
	return file_core_category_message_proto_rawDescGZIP(), []int{1}
}

func (x *CategoryStyle) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CategoryStyle) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type CategoryInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Style         *CategoryStyleInput    `protobuf:"bytes,4,opt,name=style,proto3" json:"style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryInput) Reset() {
	*x = CategoryInput{}
	mi := &file_core_category_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInput) ProtoMessage() {}

func (x *CategoryInput) ProtoReflect() protoreflect.Message {
	mi := &file_core_category_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInput.ProtoReflect.Descriptor instead.
func (*CategoryInput) Descriptor() ([]byte, []int) {
	return file_core_category_message_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryInput) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *CategoryInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryInput) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CategoryInput) GetStyle() *CategoryStyleInput {
	if x != nil {
		return x.Style
	}
	return nil
}

type CategoryStyleInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         string                 `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	Icon          string                 `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryStyleInput) Reset() {
	*x = CategoryStyleInput{}
	mi := &file_core_category_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryStyleInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryStyleInput) ProtoMessage() {}

func (x *CategoryStyleInput) ProtoReflect() protoreflect.Message {
	mi := &file_core_category_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryStyleInput.ProtoReflect.Descriptor instead.
func (*CategoryStyleInput) Descriptor() ([]byte, []int) {
	return file_core_category_message_proto_rawDescGZIP(), []int{3}
}

func (x *CategoryStyleInput) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CategoryStyleInput) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

var File_core_category_message_proto protoreflect.FileDescriptor

const file_core_category_message_proto_rawDesc = "" +
	"\n" +
	"\x1bcore/category_message.proto\x12\x04core\"\xf1\x01\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x12!\n" +
	"\fcharacter_id\x18\x04 \x01(\tR\vcharacterId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x00R\vdescription\x88\x01\x01\x12)\n" +
	"\x05style\x18\a \x01(\v2\x13.core.CategoryStyleR\x05styleB\x0e\n" +
	"\f_description\"9\n" +
	"\rCategoryStyle\x12\x14\n" +
	"\x05color\x18\x01 \x01(\tR\x05color\x12\x12\n" +
	"\x04icon\x18\x02 \x01(\tR\x04icon\"\xa6\x01\n" +
	"\rCategoryInput\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12.\n" +
	"\x05style\x18\x04 \x01(\v2\x18.core.CategoryStyleInputR\x05styleB\x05\n" +
	"\x03_idB\x0e\n" +
	"\f_description\">\n" +
	"\x12CategoryStyleInput\x12\x14\n" +
	"\x05color\x18\x01 \x01(\tR\x05color\x12\x12\n" +
	"\x04icon\x18\x02 \x01(\tR\x04iconB\x19Z\x17tenkhours/proto/pb/coreb\x06proto3"

var (
	file_core_category_message_proto_rawDescOnce sync.Once
	file_core_category_message_proto_rawDescData []byte
)

func file_core_category_message_proto_rawDescGZIP() []byte {
	file_core_category_message_proto_rawDescOnce.Do(func() {
		file_core_category_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_category_message_proto_rawDesc), len(file_core_category_message_proto_rawDesc)))
	})
	return file_core_category_message_proto_rawDescData
}

var file_core_category_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_core_category_message_proto_goTypes = []any{
	(*Category)(nil),           // 0: core.Category
	(*CategoryStyle)(nil),      // 1: core.CategoryStyle
	(*CategoryInput)(nil),      // 2: core.CategoryInput
	(*CategoryStyleInput)(nil), // 3: core.CategoryStyleInput
}
var file_core_category_message_proto_depIdxs = []int32{
	1, // 0: core.Category.style:type_name -> core.CategoryStyle
	3, // 1: core.CategoryInput.style:type_name -> core.CategoryStyleInput
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_category_message_proto_init() }
func file_core_category_message_proto_init() {
	if File_core_category_message_proto != nil {
		return
	}
	file_core_category_message_proto_msgTypes[0].OneofWrappers = []any{}
	file_core_category_message_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_category_message_proto_rawDesc), len(file_core_category_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_category_message_proto_goTypes,
		DependencyIndexes: file_core_category_message_proto_depIdxs,
		MessageInfos:      file_core_category_message_proto_msgTypes,
	}.Build()
	File_core_category_message_proto = out.File
	file_core_category_message_proto_goTypes = nil
	file_core_category_message_proto_depIdxs = nil
}
