// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: core/character_message.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Character struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ProfileId     string                 `protobuf:"bytes,4,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Character) Reset() {
	*x = Character{}
	mi := &file_core_character_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_core_character_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_core_character_message_proto_rawDescGZIP(), []int{0}
}

func (x *Character) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Character) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Character) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Character) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *Character) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Input Messages
type CharacterInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterInput) Reset() {
	*x = CharacterInput{}
	mi := &file_core_character_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterInput) ProtoMessage() {}

func (x *CharacterInput) ProtoReflect() protoreflect.Message {
	mi := &file_core_character_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterInput.ProtoReflect.Descriptor instead.
func (*CharacterInput) Descriptor() ([]byte, []int) {
	return file_core_character_message_proto_rawDescGZIP(), []int{1}
}

func (x *CharacterInput) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *CharacterInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_core_character_message_proto protoreflect.FileDescriptor

const file_core_character_message_proto_rawDesc = "" +
	"\n" +
	"\x1ccore/character_message.proto\x12\x04core\"\x8c\x01\n" +
	"\tCharacter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x04 \x01(\tR\tprofileId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"@\n" +
	"\x0eCharacterInput\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB\x05\n" +
	"\x03_idB\x19Z\x17tenkhours/proto/pb/coreb\x06proto3"

var (
	file_core_character_message_proto_rawDescOnce sync.Once
	file_core_character_message_proto_rawDescData []byte
)

func file_core_character_message_proto_rawDescGZIP() []byte {
	file_core_character_message_proto_rawDescOnce.Do(func() {
		file_core_character_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_character_message_proto_rawDesc), len(file_core_character_message_proto_rawDesc)))
	})
	return file_core_character_message_proto_rawDescData
}

var file_core_character_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_character_message_proto_goTypes = []any{
	(*Character)(nil),      // 0: core.Character
	(*CharacterInput)(nil), // 1: core.CharacterInput
}
var file_core_character_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_character_message_proto_init() }
func file_core_character_message_proto_init() {
	if File_core_character_message_proto != nil {
		return
	}
	file_core_character_message_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_character_message_proto_rawDesc), len(file_core_character_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_character_message_proto_goTypes,
		DependencyIndexes: file_core_character_message_proto_depIdxs,
		MessageInfos:      file_core_character_message_proto_msgTypes,
	}.Build()
	File_core_character_message_proto = out.File
	file_core_character_message_proto_goTypes = nil
	file_core_character_message_proto_depIdxs = nil
}
