// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: core/checkbox_message.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Checkbox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         bool                   `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkbox) Reset() {
	*x = Checkbox{}
	mi := &file_core_checkbox_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkbox) ProtoMessage() {}

func (x *Checkbox) ProtoReflect() protoreflect.Message {
	mi := &file_core_checkbox_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkbox.ProtoReflect.Descriptor instead.
func (*Checkbox) Descriptor() ([]byte, []int) {
	return file_core_checkbox_message_proto_rawDescGZIP(), []int{0}
}

func (x *Checkbox) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Checkbox) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Checkbox) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type CheckboxInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         bool                   `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckboxInput) Reset() {
	*x = CheckboxInput{}
	mi := &file_core_checkbox_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckboxInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckboxInput) ProtoMessage() {}

func (x *CheckboxInput) ProtoReflect() protoreflect.Message {
	mi := &file_core_checkbox_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckboxInput.ProtoReflect.Descriptor instead.
func (*CheckboxInput) Descriptor() ([]byte, []int) {
	return file_core_checkbox_message_proto_rawDescGZIP(), []int{1}
}

func (x *CheckboxInput) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *CheckboxInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckboxInput) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

var File_core_checkbox_message_proto protoreflect.FileDescriptor

const file_core_checkbox_message_proto_rawDesc = "" +
	"\n" +
	"\x1bcore/checkbox_message.proto\x12\x04core\"D\n" +
	"\bCheckbox\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\bR\x05value\"U\n" +
	"\rCheckboxInput\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\bR\x05valueB\x05\n" +
	"\x03_idB\x19Z\x17tenkhours/proto/pb/coreb\x06proto3"

var (
	file_core_checkbox_message_proto_rawDescOnce sync.Once
	file_core_checkbox_message_proto_rawDescData []byte
)

func file_core_checkbox_message_proto_rawDescGZIP() []byte {
	file_core_checkbox_message_proto_rawDescOnce.Do(func() {
		file_core_checkbox_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_checkbox_message_proto_rawDesc), len(file_core_checkbox_message_proto_rawDesc)))
	})
	return file_core_checkbox_message_proto_rawDescData
}

var file_core_checkbox_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_checkbox_message_proto_goTypes = []any{
	(*Checkbox)(nil),      // 0: core.Checkbox
	(*CheckboxInput)(nil), // 1: core.CheckboxInput
}
var file_core_checkbox_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_checkbox_message_proto_init() }
func file_core_checkbox_message_proto_init() {
	if File_core_checkbox_message_proto != nil {
		return
	}
	file_core_checkbox_message_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_checkbox_message_proto_rawDesc), len(file_core_checkbox_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_checkbox_message_proto_goTypes,
		DependencyIndexes: file_core_checkbox_message_proto_depIdxs,
		MessageInfos:      file_core_checkbox_message_proto_msgTypes,
	}.Build()
	File_core_checkbox_message_proto = out.File
	file_core_checkbox_message_proto_goTypes = nil
	file_core_checkbox_message_proto_depIdxs = nil
}
