// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: core/core_service.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	common "tenkhours/proto/pb/common"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_core_core_service_proto protoreflect.FileDescriptor

const file_core_core_service_proto_rawDesc = "" +
	"\n" +
	"\x17core/core_service.proto\x12\x04core\x1a\x1bcommon/common_message.proto\x1a\x1ccore/character_message.proto\x1a\x17core/goal_message.proto\x1a\x1acore/profile_message.proto\x1a\x17core/task_message.proto\x1a\x1fcore/task_session_message.proto\x1a\x1fcore/timetracking_message.proto\x1a\x18core/habit_message.proto\x1a\x1bcore/category_message.proto\x1a\x19core/metric_message.proto\x1a\x1ccore/habit_log_message.proto2\xb6\a\n" +
	"\x04Core\x12;\n" +
	"\x0eIntrospectUser\x12\x13.core.IntrospectReq\x1a\x14.core.IntrospectResp\x128\n" +
	"\x0fUpsertCharacter\x12\x14.core.CharacterInput\x1a\x0f.core.Character\x12)\n" +
	"\n" +
	"UpsertGoal\x12\x0f.core.GoalInput\x1a\n" +
	".core.Goal\x12+\n" +
	"\n" +
	"DeleteGoal\x12\r.common.IdReq\x1a\x0e.common.IdResp\x12A\n" +
	"\x12UpsertTimeTracking\x12\x17.core.TimeTrackingInput\x1a\x12.core.TimeTracking\x12,\n" +
	"\n" +
	"UpsertTask\x12\x0f.core.TaskInput\x1a\r.core.TaskMsg\x12/\n" +
	"\vUpsertTasks\x12\x10.core.TaskInputs\x1a\x0e.core.TaskMsgs\x12+\n" +
	"\n" +
	"DeleteTask\x12\r.common.IdReq\x1a\x0e.common.IdResp\x12>\n" +
	"\x11UpsertTaskSession\x12\x16.core.TaskSessionInput\x1a\x11.core.TaskSession\x12A\n" +
	"\x12UpsertTaskSessions\x12\x17.core.TaskSessionInputs\x1a\x12.core.TaskSessions\x122\n" +
	"\x11DeleteTaskSession\x12\r.common.IdReq\x1a\x0e.common.IdResp\x12,\n" +
	"\vUpsertHabit\x12\x10.core.HabitInput\x1a\v.core.Habit\x12,\n" +
	"\vDeleteHabit\x12\r.common.IdReq\x1a\x0e.common.IdResp\x125\n" +
	"\x0eUpsertHabitLog\x12\x13.core.HabitLogInput\x1a\x0e.core.HabitLog\x125\n" +
	"\x0eUpsertCategory\x12\x13.core.CategoryInput\x1a\x0e.core.Category\x12/\n" +
	"\x0eDeleteCategory\x12\r.common.IdReq\x1a\x0e.common.IdResp\x12/\n" +
	"\fUpsertMetric\x12\x11.core.MetricInput\x1a\f.core.Metric\x12-\n" +
	"\fDeleteMetric\x12\r.common.IdReq\x1a\x0e.common.IdRespB\x19Z\x17tenkhours/proto/pb/coreb\x06proto3"

var file_core_core_service_proto_goTypes = []any{
	(*IntrospectReq)(nil),     // 0: core.IntrospectReq
	(*CharacterInput)(nil),    // 1: core.CharacterInput
	(*GoalInput)(nil),         // 2: core.GoalInput
	(*common.IdReq)(nil),      // 3: common.IdReq
	(*TimeTrackingInput)(nil), // 4: core.TimeTrackingInput
	(*TaskInput)(nil),         // 5: core.TaskInput
	(*TaskInputs)(nil),        // 6: core.TaskInputs
	(*TaskSessionInput)(nil),  // 7: core.TaskSessionInput
	(*TaskSessionInputs)(nil), // 8: core.TaskSessionInputs
	(*HabitInput)(nil),        // 9: core.HabitInput
	(*HabitLogInput)(nil),     // 10: core.HabitLogInput
	(*CategoryInput)(nil),     // 11: core.CategoryInput
	(*MetricInput)(nil),       // 12: core.MetricInput
	(*IntrospectResp)(nil),    // 13: core.IntrospectResp
	(*Character)(nil),         // 14: core.Character
	(*Goal)(nil),              // 15: core.Goal
	(*common.IdResp)(nil),     // 16: common.IdResp
	(*TimeTracking)(nil),      // 17: core.TimeTracking
	(*TaskMsg)(nil),           // 18: core.TaskMsg
	(*TaskMsgs)(nil),          // 19: core.TaskMsgs
	(*TaskSession)(nil),       // 20: core.TaskSession
	(*TaskSessions)(nil),      // 21: core.TaskSessions
	(*Habit)(nil),             // 22: core.Habit
	(*HabitLog)(nil),          // 23: core.HabitLog
	(*Category)(nil),          // 24: core.Category
	(*Metric)(nil),            // 25: core.Metric
}
var file_core_core_service_proto_depIdxs = []int32{
	0,  // 0: core.Core.IntrospectUser:input_type -> core.IntrospectReq
	1,  // 1: core.Core.UpsertCharacter:input_type -> core.CharacterInput
	2,  // 2: core.Core.UpsertGoal:input_type -> core.GoalInput
	3,  // 3: core.Core.DeleteGoal:input_type -> common.IdReq
	4,  // 4: core.Core.UpsertTimeTracking:input_type -> core.TimeTrackingInput
	5,  // 5: core.Core.UpsertTask:input_type -> core.TaskInput
	6,  // 6: core.Core.UpsertTasks:input_type -> core.TaskInputs
	3,  // 7: core.Core.DeleteTask:input_type -> common.IdReq
	7,  // 8: core.Core.UpsertTaskSession:input_type -> core.TaskSessionInput
	8,  // 9: core.Core.UpsertTaskSessions:input_type -> core.TaskSessionInputs
	3,  // 10: core.Core.DeleteTaskSession:input_type -> common.IdReq
	9,  // 11: core.Core.UpsertHabit:input_type -> core.HabitInput
	3,  // 12: core.Core.DeleteHabit:input_type -> common.IdReq
	10, // 13: core.Core.UpsertHabitLog:input_type -> core.HabitLogInput
	11, // 14: core.Core.UpsertCategory:input_type -> core.CategoryInput
	3,  // 15: core.Core.DeleteCategory:input_type -> common.IdReq
	12, // 16: core.Core.UpsertMetric:input_type -> core.MetricInput
	3,  // 17: core.Core.DeleteMetric:input_type -> common.IdReq
	13, // 18: core.Core.IntrospectUser:output_type -> core.IntrospectResp
	14, // 19: core.Core.UpsertCharacter:output_type -> core.Character
	15, // 20: core.Core.UpsertGoal:output_type -> core.Goal
	16, // 21: core.Core.DeleteGoal:output_type -> common.IdResp
	17, // 22: core.Core.UpsertTimeTracking:output_type -> core.TimeTracking
	18, // 23: core.Core.UpsertTask:output_type -> core.TaskMsg
	19, // 24: core.Core.UpsertTasks:output_type -> core.TaskMsgs
	16, // 25: core.Core.DeleteTask:output_type -> common.IdResp
	20, // 26: core.Core.UpsertTaskSession:output_type -> core.TaskSession
	21, // 27: core.Core.UpsertTaskSessions:output_type -> core.TaskSessions
	16, // 28: core.Core.DeleteTaskSession:output_type -> common.IdResp
	22, // 29: core.Core.UpsertHabit:output_type -> core.Habit
	16, // 30: core.Core.DeleteHabit:output_type -> common.IdResp
	23, // 31: core.Core.UpsertHabitLog:output_type -> core.HabitLog
	24, // 32: core.Core.UpsertCategory:output_type -> core.Category
	16, // 33: core.Core.DeleteCategory:output_type -> common.IdResp
	25, // 34: core.Core.UpsertMetric:output_type -> core.Metric
	16, // 35: core.Core.DeleteMetric:output_type -> common.IdResp
	18, // [18:36] is the sub-list for method output_type
	0,  // [0:18] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_core_core_service_proto_init() }
func file_core_core_service_proto_init() {
	if File_core_core_service_proto != nil {
		return
	}
	file_core_character_message_proto_init()
	file_core_goal_message_proto_init()
	file_core_profile_message_proto_init()
	file_core_task_message_proto_init()
	file_core_task_session_message_proto_init()
	file_core_timetracking_message_proto_init()
	file_core_habit_message_proto_init()
	file_core_category_message_proto_init()
	file_core_metric_message_proto_init()
	file_core_habit_log_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_core_service_proto_rawDesc), len(file_core_core_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_core_service_proto_goTypes,
		DependencyIndexes: file_core_core_service_proto_depIdxs,
	}.Build()
	File_core_core_service_proto = out.File
	file_core_core_service_proto_goTypes = nil
	file_core_core_service_proto_depIdxs = nil
}
