// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: core/core_service.proto

package core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "tenkhours/proto/pb/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Core_IntrospectToken_FullMethodName             = "/core.Core/IntrospectToken"
	Core_UpsertCharacter_FullMethodName             = "/core.Core/UpsertCharacter"
	Core_UpsertGoal_FullMethodName                  = "/core.Core/UpsertGoal"
	Core_GetCurrentTimeTracking_FullMethodName      = "/core.Core/GetCurrentTimeTracking"
	Core_GetTotalCurrentTimeTracking_FullMethodName = "/core.Core/GetTotalCurrentTimeTracking"
	Core_CreateTimeTracking_FullMethodName          = "/core.Core/CreateTimeTracking"
	Core_UpdateTimeTracking_FullMethodName          = "/core.Core/UpdateTimeTracking"
)

// CoreClient is the client API for Core service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreClient interface {
	IntrospectToken(ctx context.Context, in *IntrospectReq, opts ...grpc.CallOption) (*IntrospectResp, error)
	UpsertCharacter(ctx context.Context, in *CharacterInput, opts ...grpc.CallOption) (*Character, error)
	UpsertGoal(ctx context.Context, in *GoalInput, opts ...grpc.CallOption) (*Goal, error)
	GetCurrentTimeTracking(ctx context.Context, in *common.EmptyReq, opts ...grpc.CallOption) (*TimeTracking, error)
	GetTotalCurrentTimeTracking(ctx context.Context, in *TotalTimeTrackingReq, opts ...grpc.CallOption) (*TotalTimeTrackingResp, error)
	CreateTimeTracking(ctx context.Context, in *CreateTimeTrackingReq, opts ...grpc.CallOption) (*TimeTracking, error)
	UpdateTimeTracking(ctx context.Context, in *common.EmptyReq, opts ...grpc.CallOption) (*TimeTracking, error)
}

type coreClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreClient(cc grpc.ClientConnInterface) CoreClient {
	return &coreClient{cc}
}

func (c *coreClient) IntrospectToken(ctx context.Context, in *IntrospectReq, opts ...grpc.CallOption) (*IntrospectResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntrospectResp)
	err := c.cc.Invoke(ctx, Core_IntrospectToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) UpsertCharacter(ctx context.Context, in *CharacterInput, opts ...grpc.CallOption) (*Character, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Character)
	err := c.cc.Invoke(ctx, Core_UpsertCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) UpsertGoal(ctx context.Context, in *GoalInput, opts ...grpc.CallOption) (*Goal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Goal)
	err := c.cc.Invoke(ctx, Core_UpsertGoal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) GetCurrentTimeTracking(ctx context.Context, in *common.EmptyReq, opts ...grpc.CallOption) (*TimeTracking, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeTracking)
	err := c.cc.Invoke(ctx, Core_GetCurrentTimeTracking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) GetTotalCurrentTimeTracking(ctx context.Context, in *TotalTimeTrackingReq, opts ...grpc.CallOption) (*TotalTimeTrackingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TotalTimeTrackingResp)
	err := c.cc.Invoke(ctx, Core_GetTotalCurrentTimeTracking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) CreateTimeTracking(ctx context.Context, in *CreateTimeTrackingReq, opts ...grpc.CallOption) (*TimeTracking, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeTracking)
	err := c.cc.Invoke(ctx, Core_CreateTimeTracking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) UpdateTimeTracking(ctx context.Context, in *common.EmptyReq, opts ...grpc.CallOption) (*TimeTracking, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TimeTracking)
	err := c.cc.Invoke(ctx, Core_UpdateTimeTracking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreServer is the server API for Core service.
// All implementations must embed UnimplementedCoreServer
// for forward compatibility.
type CoreServer interface {
	IntrospectToken(context.Context, *IntrospectReq) (*IntrospectResp, error)
	UpsertCharacter(context.Context, *CharacterInput) (*Character, error)
	UpsertGoal(context.Context, *GoalInput) (*Goal, error)
	GetCurrentTimeTracking(context.Context, *common.EmptyReq) (*TimeTracking, error)
	GetTotalCurrentTimeTracking(context.Context, *TotalTimeTrackingReq) (*TotalTimeTrackingResp, error)
	CreateTimeTracking(context.Context, *CreateTimeTrackingReq) (*TimeTracking, error)
	UpdateTimeTracking(context.Context, *common.EmptyReq) (*TimeTracking, error)
	mustEmbedUnimplementedCoreServer()
}

// UnimplementedCoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreServer struct{}

func (UnimplementedCoreServer) IntrospectToken(context.Context, *IntrospectReq) (*IntrospectResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IntrospectToken not implemented")
}
func (UnimplementedCoreServer) UpsertCharacter(context.Context, *CharacterInput) (*Character, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertCharacter not implemented")
}
func (UnimplementedCoreServer) UpsertGoal(context.Context, *GoalInput) (*Goal, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertGoal not implemented")
}
func (UnimplementedCoreServer) GetCurrentTimeTracking(context.Context, *common.EmptyReq) (*TimeTracking, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentTimeTracking not implemented")
}
func (UnimplementedCoreServer) GetTotalCurrentTimeTracking(context.Context, *TotalTimeTrackingReq) (*TotalTimeTrackingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTotalCurrentTimeTracking not implemented")
}
func (UnimplementedCoreServer) CreateTimeTracking(context.Context, *CreateTimeTrackingReq) (*TimeTracking, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTimeTracking not implemented")
}
func (UnimplementedCoreServer) UpdateTimeTracking(context.Context, *common.EmptyReq) (*TimeTracking, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTimeTracking not implemented")
}
func (UnimplementedCoreServer) mustEmbedUnimplementedCoreServer() {}
func (UnimplementedCoreServer) testEmbeddedByValue()              {}

// UnsafeCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreServer will
// result in compilation errors.
type UnsafeCoreServer interface {
	mustEmbedUnimplementedCoreServer()
}

func RegisterCoreServer(s grpc.ServiceRegistrar, srv CoreServer) {
	// If the following call pancis, it indicates UnimplementedCoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Core_ServiceDesc, srv)
}

func _Core_IntrospectToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntrospectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).IntrospectToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_IntrospectToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).IntrospectToken(ctx, req.(*IntrospectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_UpsertCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CharacterInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).UpsertCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_UpsertCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).UpsertCharacter(ctx, req.(*CharacterInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_UpsertGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoalInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).UpsertGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_UpsertGoal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).UpsertGoal(ctx, req.(*GoalInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_GetCurrentTimeTracking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GetCurrentTimeTracking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_GetCurrentTimeTracking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GetCurrentTimeTracking(ctx, req.(*common.EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_GetTotalCurrentTimeTracking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TotalTimeTrackingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).GetTotalCurrentTimeTracking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_GetTotalCurrentTimeTracking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).GetTotalCurrentTimeTracking(ctx, req.(*TotalTimeTrackingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_CreateTimeTracking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTimeTrackingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).CreateTimeTracking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_CreateTimeTracking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).CreateTimeTracking(ctx, req.(*CreateTimeTrackingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_UpdateTimeTracking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).UpdateTimeTracking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Core_UpdateTimeTracking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).UpdateTimeTracking(ctx, req.(*common.EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Core_ServiceDesc is the grpc.ServiceDesc for Core service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Core_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.Core",
	HandlerType: (*CoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IntrospectToken",
			Handler:    _Core_IntrospectToken_Handler,
		},
		{
			MethodName: "UpsertCharacter",
			Handler:    _Core_UpsertCharacter_Handler,
		},
		{
			MethodName: "UpsertGoal",
			Handler:    _Core_UpsertGoal_Handler,
		},
		{
			MethodName: "GetCurrentTimeTracking",
			Handler:    _Core_GetCurrentTimeTracking_Handler,
		},
		{
			MethodName: "GetTotalCurrentTimeTracking",
			Handler:    _Core_GetTotalCurrentTimeTracking_Handler,
		},
		{
			MethodName: "CreateTimeTracking",
			Handler:    _Core_CreateTimeTracking_Handler,
		},
		{
			MethodName: "UpdateTimeTracking",
			Handler:    _Core_UpdateTimeTracking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/core_service.proto",
}
