// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: core/core_service.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	common "tenkhours/proto/pb/common"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_core_core_service_proto protoreflect.FileDescriptor

const file_core_core_service_proto_rawDesc = "" +
	"\n" +
	"\x17core/core_service.proto\x12\x04core\x1a\x1bcommon/common_message.proto\x1a\x1ccore/character_message.proto\x1a\x17core/goal_message.proto\x1a\x1acore/profile_message.proto\x1a\x17core/task_message.proto\x1a\x1fcore/task_session_message.proto\x1a\x1fcore/timetracking_message.proto2\xdb\x04\n" +
	"\x04Core\x12;\n" +
	"\x0eIntrospectUser\x12\x13.core.IntrospectReq\x1a\x14.core.IntrospectResp\x128\n" +
	"\x0fUpsertCharacter\x12\x14.core.CharacterInput\x1a\x0f.core.Character\x12)\n" +
	"\n" +
	"UpsertGoal\x12\x0f.core.GoalInput\x1a\n" +
	".core.Goal\x12+\n" +
	"\n" +
	"DeleteGoal\x12\r.common.IdReq\x1a\x0e.common.IdResp\x12A\n" +
	"\x12UpsertTimeTracking\x12\x17.core.TimeTrackingInput\x1a\x12.core.TimeTracking\x12,\n" +
	"\n" +
	"UpsertTask\x12\x0f.core.TaskInput\x1a\r.core.TaskMsg\x12/\n" +
	"\vUpsertTasks\x12\x10.core.TaskInputs\x1a\x0e.core.TaskMsgs\x12+\n" +
	"\n" +
	"DeleteTask\x12\r.common.IdReq\x1a\x0e.common.IdResp\x12>\n" +
	"\x11UpsertTaskSession\x12\x16.core.TaskSessionInput\x1a\x11.core.TaskSession\x12A\n" +
	"\x12UpsertTaskSessions\x12\x17.core.TaskSessionInputs\x1a\x12.core.TaskSessions\x122\n" +
	"\x11DeleteTaskSession\x12\r.common.IdReq\x1a\x0e.common.IdRespB\x19Z\x17tenkhours/proto/pb/coreb\x06proto3"

var file_core_core_service_proto_goTypes = []any{
	(*IntrospectReq)(nil),     // 0: core.IntrospectReq
	(*CharacterInput)(nil),    // 1: core.CharacterInput
	(*GoalInput)(nil),         // 2: core.GoalInput
	(*common.IdReq)(nil),      // 3: common.IdReq
	(*TimeTrackingInput)(nil), // 4: core.TimeTrackingInput
	(*TaskInput)(nil),         // 5: core.TaskInput
	(*TaskInputs)(nil),        // 6: core.TaskInputs
	(*TaskSessionInput)(nil),  // 7: core.TaskSessionInput
	(*TaskSessionInputs)(nil), // 8: core.TaskSessionInputs
	(*IntrospectResp)(nil),    // 9: core.IntrospectResp
	(*Character)(nil),         // 10: core.Character
	(*Goal)(nil),              // 11: core.Goal
	(*common.IdResp)(nil),     // 12: common.IdResp
	(*TimeTracking)(nil),      // 13: core.TimeTracking
	(*TaskMsg)(nil),           // 14: core.TaskMsg
	(*TaskMsgs)(nil),          // 15: core.TaskMsgs
	(*TaskSession)(nil),       // 16: core.TaskSession
	(*TaskSessions)(nil),      // 17: core.TaskSessions
}
var file_core_core_service_proto_depIdxs = []int32{
	0,  // 0: core.Core.IntrospectUser:input_type -> core.IntrospectReq
	1,  // 1: core.Core.UpsertCharacter:input_type -> core.CharacterInput
	2,  // 2: core.Core.UpsertGoal:input_type -> core.GoalInput
	3,  // 3: core.Core.DeleteGoal:input_type -> common.IdReq
	4,  // 4: core.Core.UpsertTimeTracking:input_type -> core.TimeTrackingInput
	5,  // 5: core.Core.UpsertTask:input_type -> core.TaskInput
	6,  // 6: core.Core.UpsertTasks:input_type -> core.TaskInputs
	3,  // 7: core.Core.DeleteTask:input_type -> common.IdReq
	7,  // 8: core.Core.UpsertTaskSession:input_type -> core.TaskSessionInput
	8,  // 9: core.Core.UpsertTaskSessions:input_type -> core.TaskSessionInputs
	3,  // 10: core.Core.DeleteTaskSession:input_type -> common.IdReq
	9,  // 11: core.Core.IntrospectUser:output_type -> core.IntrospectResp
	10, // 12: core.Core.UpsertCharacter:output_type -> core.Character
	11, // 13: core.Core.UpsertGoal:output_type -> core.Goal
	12, // 14: core.Core.DeleteGoal:output_type -> common.IdResp
	13, // 15: core.Core.UpsertTimeTracking:output_type -> core.TimeTracking
	14, // 16: core.Core.UpsertTask:output_type -> core.TaskMsg
	15, // 17: core.Core.UpsertTasks:output_type -> core.TaskMsgs
	12, // 18: core.Core.DeleteTask:output_type -> common.IdResp
	16, // 19: core.Core.UpsertTaskSession:output_type -> core.TaskSession
	17, // 20: core.Core.UpsertTaskSessions:output_type -> core.TaskSessions
	12, // 21: core.Core.DeleteTaskSession:output_type -> common.IdResp
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_core_core_service_proto_init() }
func file_core_core_service_proto_init() {
	if File_core_core_service_proto != nil {
		return
	}
	file_core_character_message_proto_init()
	file_core_goal_message_proto_init()
	file_core_profile_message_proto_init()
	file_core_task_message_proto_init()
	file_core_task_session_message_proto_init()
	file_core_timetracking_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_core_service_proto_rawDesc), len(file_core_core_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_core_service_proto_goTypes,
		DependencyIndexes: file_core_core_service_proto_depIdxs,
	}.Build()
	File_core_core_service_proto = out.File
	file_core_core_service_proto_goTypes = nil
	file_core_core_service_proto_depIdxs = nil
}
