// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: core/habit_message.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompletionType int32

const (
	CompletionType_Number CompletionType = 0
	CompletionType_Time   CompletionType = 1
)

// Enum value maps for CompletionType.
var (
	CompletionType_name = map[int32]string{
		0: "Number",
		1: "Time",
	}
	CompletionType_value = map[string]int32{
		"Number": 0,
		"Time":   1,
	}
)

func (x CompletionType) Enum() *CompletionType {
	p := new(CompletionType)
	*p = x
	return p
}

func (x CompletionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompletionType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_habit_message_proto_enumTypes[0].Descriptor()
}

func (CompletionType) Type() protoreflect.EnumType {
	return &file_core_habit_message_proto_enumTypes[0]
}

func (x CompletionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompletionType.Descriptor instead.
func (CompletionType) EnumDescriptor() ([]byte, []int) {
	return file_core_habit_message_proto_rawDescGZIP(), []int{0}
}

type HabitReset int32

const (
	HabitReset_Daily   HabitReset = 0
	HabitReset_Weekly  HabitReset = 1
	HabitReset_Monthly HabitReset = 2
)

// Enum value maps for HabitReset.
var (
	HabitReset_name = map[int32]string{
		0: "Daily",
		1: "Weekly",
		2: "Monthly",
	}
	HabitReset_value = map[string]int32{
		"Daily":   0,
		"Weekly":  1,
		"Monthly": 2,
	}
)

func (x HabitReset) Enum() *HabitReset {
	p := new(HabitReset)
	*p = x
	return p
}

func (x HabitReset) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HabitReset) Descriptor() protoreflect.EnumDescriptor {
	return file_core_habit_message_proto_enumTypes[1].Descriptor()
}

func (HabitReset) Type() protoreflect.EnumType {
	return &file_core_habit_message_proto_enumTypes[1]
}

func (x HabitReset) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HabitReset.Descriptor instead.
func (HabitReset) EnumDescriptor() ([]byte, []int) {
	return file_core_habit_message_proto_rawDescGZIP(), []int{1}
}

type Habit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CharacterId    string                 `protobuf:"bytes,4,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	CategoryId     *string                `protobuf:"bytes,5,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	CompletionType CompletionType         `protobuf:"varint,6,opt,name=completion_type,json=completionType,proto3,enum=core.CompletionType" json:"completion_type,omitempty"`
	Name           string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Value          float32                `protobuf:"fixed32,8,opt,name=value,proto3" json:"value,omitempty"`
	Unit           *string                `protobuf:"bytes,9,opt,name=unit,proto3,oneof" json:"unit,omitempty"`
	Rrule          string                 `protobuf:"bytes,10,opt,name=rrule,proto3" json:"rrule,omitempty"`
	ResetDuration  HabitReset             `protobuf:"varint,11,opt,name=reset_duration,json=resetDuration,proto3,enum=core.HabitReset" json:"reset_duration,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Habit) Reset() {
	*x = Habit{}
	mi := &file_core_habit_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Habit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Habit) ProtoMessage() {}

func (x *Habit) ProtoReflect() protoreflect.Message {
	mi := &file_core_habit_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Habit.ProtoReflect.Descriptor instead.
func (*Habit) Descriptor() ([]byte, []int) {
	return file_core_habit_message_proto_rawDescGZIP(), []int{0}
}

func (x *Habit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Habit) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Habit) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Habit) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *Habit) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *Habit) GetCompletionType() CompletionType {
	if x != nil {
		return x.CompletionType
	}
	return CompletionType_Number
}

func (x *Habit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Habit) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Habit) GetUnit() string {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return ""
}

func (x *Habit) GetRrule() string {
	if x != nil {
		return x.Rrule
	}
	return ""
}

func (x *Habit) GetResetDuration() HabitReset {
	if x != nil {
		return x.ResetDuration
	}
	return HabitReset_Daily
}

type HabitInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	CategoryId     *string                `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	CompletionType CompletionType         `protobuf:"varint,3,opt,name=completion_type,json=completionType,proto3,enum=core.CompletionType" json:"completion_type,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Value          float32                `protobuf:"fixed32,5,opt,name=value,proto3" json:"value,omitempty"`
	Unit           *string                `protobuf:"bytes,6,opt,name=unit,proto3,oneof" json:"unit,omitempty"`
	Rrule          string                 `protobuf:"bytes,7,opt,name=rrule,proto3" json:"rrule,omitempty"`
	ResetDuration  HabitReset             `protobuf:"varint,8,opt,name=reset_duration,json=resetDuration,proto3,enum=core.HabitReset" json:"reset_duration,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HabitInput) Reset() {
	*x = HabitInput{}
	mi := &file_core_habit_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HabitInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HabitInput) ProtoMessage() {}

func (x *HabitInput) ProtoReflect() protoreflect.Message {
	mi := &file_core_habit_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HabitInput.ProtoReflect.Descriptor instead.
func (*HabitInput) Descriptor() ([]byte, []int) {
	return file_core_habit_message_proto_rawDescGZIP(), []int{1}
}

func (x *HabitInput) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *HabitInput) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *HabitInput) GetCompletionType() CompletionType {
	if x != nil {
		return x.CompletionType
	}
	return CompletionType_Number
}

func (x *HabitInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HabitInput) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *HabitInput) GetUnit() string {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return ""
}

func (x *HabitInput) GetRrule() string {
	if x != nil {
		return x.Rrule
	}
	return ""
}

func (x *HabitInput) GetResetDuration() HabitReset {
	if x != nil {
		return x.ResetDuration
	}
	return HabitReset_Daily
}

var File_core_habit_message_proto protoreflect.FileDescriptor

const file_core_habit_message_proto_rawDesc = "" +
	"\n" +
	"\x18core/habit_message.proto\x12\x04core\"\x88\x03\n" +
	"\x05Habit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x12!\n" +
	"\fcharacter_id\x18\x04 \x01(\tR\vcharacterId\x12$\n" +
	"\vcategory_id\x18\x05 \x01(\tH\x00R\n" +
	"categoryId\x88\x01\x01\x12=\n" +
	"\x0fcompletion_type\x18\x06 \x01(\x0e2\x14.core.CompletionTypeR\x0ecompletionType\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\b \x01(\x02R\x05value\x12\x17\n" +
	"\x04unit\x18\t \x01(\tH\x01R\x04unit\x88\x01\x01\x12\x14\n" +
	"\x05rrule\x18\n" +
	" \x01(\tR\x05rrule\x127\n" +
	"\x0ereset_duration\x18\v \x01(\x0e2\x10.core.HabitResetR\rresetDurationB\x0e\n" +
	"\f_category_idB\a\n" +
	"\x05_unit\"\xb8\x02\n" +
	"\n" +
	"HabitInput\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12$\n" +
	"\vcategory_id\x18\x02 \x01(\tH\x01R\n" +
	"categoryId\x88\x01\x01\x12=\n" +
	"\x0fcompletion_type\x18\x03 \x01(\x0e2\x14.core.CompletionTypeR\x0ecompletionType\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x02R\x05value\x12\x17\n" +
	"\x04unit\x18\x06 \x01(\tH\x02R\x04unit\x88\x01\x01\x12\x14\n" +
	"\x05rrule\x18\a \x01(\tR\x05rrule\x127\n" +
	"\x0ereset_duration\x18\b \x01(\x0e2\x10.core.HabitResetR\rresetDurationB\x05\n" +
	"\x03_idB\x0e\n" +
	"\f_category_idB\a\n" +
	"\x05_unit*&\n" +
	"\x0eCompletionType\x12\n" +
	"\n" +
	"\x06Number\x10\x00\x12\b\n" +
	"\x04Time\x10\x01*0\n" +
	"\n" +
	"HabitReset\x12\t\n" +
	"\x05Daily\x10\x00\x12\n" +
	"\n" +
	"\x06Weekly\x10\x01\x12\v\n" +
	"\aMonthly\x10\x02B\x19Z\x17tenkhours/proto/pb/coreb\x06proto3"

var (
	file_core_habit_message_proto_rawDescOnce sync.Once
	file_core_habit_message_proto_rawDescData []byte
)

func file_core_habit_message_proto_rawDescGZIP() []byte {
	file_core_habit_message_proto_rawDescOnce.Do(func() {
		file_core_habit_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_habit_message_proto_rawDesc), len(file_core_habit_message_proto_rawDesc)))
	})
	return file_core_habit_message_proto_rawDescData
}

var file_core_habit_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_core_habit_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_habit_message_proto_goTypes = []any{
	(CompletionType)(0), // 0: core.CompletionType
	(HabitReset)(0),     // 1: core.HabitReset
	(*Habit)(nil),       // 2: core.Habit
	(*HabitInput)(nil),  // 3: core.HabitInput
}
var file_core_habit_message_proto_depIdxs = []int32{
	0, // 0: core.Habit.completion_type:type_name -> core.CompletionType
	1, // 1: core.Habit.reset_duration:type_name -> core.HabitReset
	0, // 2: core.HabitInput.completion_type:type_name -> core.CompletionType
	1, // 3: core.HabitInput.reset_duration:type_name -> core.HabitReset
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_core_habit_message_proto_init() }
func file_core_habit_message_proto_init() {
	if File_core_habit_message_proto != nil {
		return
	}
	file_core_habit_message_proto_msgTypes[0].OneofWrappers = []any{}
	file_core_habit_message_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_habit_message_proto_rawDesc), len(file_core_habit_message_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_habit_message_proto_goTypes,
		DependencyIndexes: file_core_habit_message_proto_depIdxs,
		EnumInfos:         file_core_habit_message_proto_enumTypes,
		MessageInfos:      file_core_habit_message_proto_msgTypes,
	}.Build()
	File_core_habit_message_proto = out.File
	file_core_habit_message_proto_goTypes = nil
	file_core_habit_message_proto_depIdxs = nil
}
