// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: core/habit_log_message.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HabitLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	HabitId       string                 `protobuf:"bytes,3,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	Value         float32                `protobuf:"fixed32,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HabitLog) Reset() {
	*x = HabitLog{}
	mi := &file_core_habit_log_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HabitLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HabitLog) ProtoMessage() {}

func (x *HabitLog) ProtoReflect() protoreflect.Message {
	mi := &file_core_habit_log_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HabitLog.ProtoReflect.Descriptor instead.
func (*HabitLog) Descriptor() ([]byte, []int) {
	return file_core_habit_log_message_proto_rawDescGZIP(), []int{0}
}

func (x *HabitLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HabitLog) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *HabitLog) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *HabitLog) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type HabitLogInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	HabitId       string                 `protobuf:"bytes,2,opt,name=habit_id,json=habitId,proto3" json:"habit_id,omitempty"`
	Value         float32                `protobuf:"fixed32,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HabitLogInput) Reset() {
	*x = HabitLogInput{}
	mi := &file_core_habit_log_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HabitLogInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HabitLogInput) ProtoMessage() {}

func (x *HabitLogInput) ProtoReflect() protoreflect.Message {
	mi := &file_core_habit_log_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HabitLogInput.ProtoReflect.Descriptor instead.
func (*HabitLogInput) Descriptor() ([]byte, []int) {
	return file_core_habit_log_message_proto_rawDescGZIP(), []int{1}
}

func (x *HabitLogInput) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *HabitLogInput) GetHabitId() string {
	if x != nil {
		return x.HabitId
	}
	return ""
}

func (x *HabitLogInput) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_core_habit_log_message_proto protoreflect.FileDescriptor

const file_core_habit_log_message_proto_rawDesc = "" +
	"\n" +
	"\x1ccore/habit_log_message.proto\x12\x04core\"i\n" +
	"\bHabitLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x19\n" +
	"\bhabit_id\x18\x03 \x01(\tR\ahabitId\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x02R\x05value\"^\n" +
	"\rHabitLogInput\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x19\n" +
	"\bhabit_id\x18\x02 \x01(\tR\ahabitId\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x02R\x05valueB\x19Z\x17tenkhours/proto/pb/coreb\x06proto3"

var (
	file_core_habit_log_message_proto_rawDescOnce sync.Once
	file_core_habit_log_message_proto_rawDescData []byte
)

func file_core_habit_log_message_proto_rawDescGZIP() []byte {
	file_core_habit_log_message_proto_rawDescOnce.Do(func() {
		file_core_habit_log_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_habit_log_message_proto_rawDesc), len(file_core_habit_log_message_proto_rawDesc)))
	})
	return file_core_habit_log_message_proto_rawDescData
}

var file_core_habit_log_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_habit_log_message_proto_goTypes = []any{
	(*HabitLog)(nil),      // 0: core.HabitLog
	(*HabitLogInput)(nil), // 1: core.HabitLogInput
}
var file_core_habit_log_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_habit_log_message_proto_init() }
func file_core_habit_log_message_proto_init() {
	if File_core_habit_log_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_habit_log_message_proto_rawDesc), len(file_core_habit_log_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_habit_log_message_proto_goTypes,
		DependencyIndexes: file_core_habit_log_message_proto_depIdxs,
		MessageInfos:      file_core_habit_log_message_proto_msgTypes,
	}.Build()
	File_core_habit_log_message_proto = out.File
	file_core_habit_log_message_proto_goTypes = nil
	file_core_habit_log_message_proto_depIdxs = nil
}
