// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: core/profile_message.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntrospectReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectReq) Reset() {
	*x = IntrospectReq{}
	mi := &file_core_profile_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectReq) ProtoMessage() {}

func (x *IntrospectReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_profile_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectReq.ProtoReflect.Descriptor instead.
func (*IntrospectReq) Descriptor() ([]byte, []int) {
	return file_core_profile_message_proto_rawDescGZIP(), []int{0}
}

func (x *IntrospectReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *IntrospectReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IntrospectReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type IntrospectResp struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ProfileId          string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	DeviceId           string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	CurrentCharacterId string                 `protobuf:"bytes,4,opt,name=current_character_id,json=currentCharacterId,proto3" json:"current_character_id,omitempty"`
	FirebaseUid        string                 `protobuf:"bytes,5,opt,name=firebase_uid,json=firebaseUid,proto3" json:"firebase_uid,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *IntrospectResp) Reset() {
	*x = IntrospectResp{}
	mi := &file_core_profile_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectResp) ProtoMessage() {}

func (x *IntrospectResp) ProtoReflect() protoreflect.Message {
	mi := &file_core_profile_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectResp.ProtoReflect.Descriptor instead.
func (*IntrospectResp) Descriptor() ([]byte, []int) {
	return file_core_profile_message_proto_rawDescGZIP(), []int{1}
}

func (x *IntrospectResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IntrospectResp) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *IntrospectResp) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *IntrospectResp) GetCurrentCharacterId() string {
	if x != nil {
		return x.CurrentCharacterId
	}
	return ""
}

func (x *IntrospectResp) GetFirebaseUid() string {
	if x != nil {
		return x.FirebaseUid
	}
	return ""
}

var File_core_profile_message_proto protoreflect.FileDescriptor

const file_core_profile_message_proto_rawDesc = "" +
	"\n" +
	"\x1acore/profile_message.proto\x12\x04core\"[\n" +
	"\rIntrospectReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\"\xbb\x01\n" +
	"\x0eIntrospectResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x120\n" +
	"\x14current_character_id\x18\x04 \x01(\tR\x12currentCharacterId\x12!\n" +
	"\ffirebase_uid\x18\x05 \x01(\tR\vfirebaseUidB\x19Z\x17tenkhours/proto/pb/coreb\x06proto3"

var (
	file_core_profile_message_proto_rawDescOnce sync.Once
	file_core_profile_message_proto_rawDescData []byte
)

func file_core_profile_message_proto_rawDescGZIP() []byte {
	file_core_profile_message_proto_rawDescOnce.Do(func() {
		file_core_profile_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_profile_message_proto_rawDesc), len(file_core_profile_message_proto_rawDesc)))
	})
	return file_core_profile_message_proto_rawDescData
}

var file_core_profile_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_profile_message_proto_goTypes = []any{
	(*IntrospectReq)(nil),  // 0: core.IntrospectReq
	(*IntrospectResp)(nil), // 1: core.IntrospectResp
}
var file_core_profile_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_profile_message_proto_init() }
func file_core_profile_message_proto_init() {
	if File_core_profile_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_profile_message_proto_rawDesc), len(file_core_profile_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_profile_message_proto_goTypes,
		DependencyIndexes: file_core_profile_message_proto_depIdxs,
		MessageInfos:      file_core_profile_message_proto_msgTypes,
	}.Build()
	File_core_profile_message_proto = out.File
	file_core_profile_message_proto_goTypes = nil
	file_core_profile_message_proto_depIdxs = nil
}
