// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: core/task_message.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CharacterId   string                 `protobuf:"bytes,4,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	CategoryId    *string                `protobuf:"bytes,5,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	CompletedTime *int64                 `protobuf:"varint,8,opt,name=completed_time,json=completedTime,proto3,oneof" json:"completed_time,omitempty"`
	Subtasks      []*Checkbox            `protobuf:"bytes,9,rep,name=subtasks,proto3" json:"subtasks,omitempty"`
	Description   *string                `protobuf:"bytes,10,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Deadline      *int64                 `protobuf:"varint,11,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMsg) Reset() {
	*x = TaskMsg{}
	mi := &file_core_task_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMsg) ProtoMessage() {}

func (x *TaskMsg) ProtoReflect() protoreflect.Message {
	mi := &file_core_task_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMsg.ProtoReflect.Descriptor instead.
func (*TaskMsg) Descriptor() ([]byte, []int) {
	return file_core_task_message_proto_rawDescGZIP(), []int{0}
}

func (x *TaskMsg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskMsg) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TaskMsg) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *TaskMsg) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *TaskMsg) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *TaskMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskMsg) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TaskMsg) GetCompletedTime() int64 {
	if x != nil && x.CompletedTime != nil {
		return *x.CompletedTime
	}
	return 0
}

func (x *TaskMsg) GetSubtasks() []*Checkbox {
	if x != nil {
		return x.Subtasks
	}
	return nil
}

func (x *TaskMsg) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *TaskMsg) GetDeadline() int64 {
	if x != nil && x.Deadline != nil {
		return *x.Deadline
	}
	return 0
}

type TaskMsgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskMsg             `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskMsgs) Reset() {
	*x = TaskMsgs{}
	mi := &file_core_task_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskMsgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMsgs) ProtoMessage() {}

func (x *TaskMsgs) ProtoReflect() protoreflect.Message {
	mi := &file_core_task_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMsgs.ProtoReflect.Descriptor instead.
func (*TaskMsgs) Descriptor() ([]byte, []int) {
	return file_core_task_message_proto_rawDescGZIP(), []int{1}
}

func (x *TaskMsgs) GetTasks() []*TaskMsg {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	CategoryId    *string                `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	CompletedTime *int64                 `protobuf:"varint,5,opt,name=completed_time,json=completedTime,proto3,oneof" json:"completed_time,omitempty"`
	Subtasks      []*CheckboxInput       `protobuf:"bytes,6,rep,name=subtasks,proto3" json:"subtasks,omitempty"`
	Description   *string                `protobuf:"bytes,7,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Deadline      *int64                 `protobuf:"varint,8,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInput) Reset() {
	*x = TaskInput{}
	mi := &file_core_task_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInput) ProtoMessage() {}

func (x *TaskInput) ProtoReflect() protoreflect.Message {
	mi := &file_core_task_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInput.ProtoReflect.Descriptor instead.
func (*TaskInput) Descriptor() ([]byte, []int) {
	return file_core_task_message_proto_rawDescGZIP(), []int{2}
}

func (x *TaskInput) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *TaskInput) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *TaskInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskInput) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TaskInput) GetCompletedTime() int64 {
	if x != nil && x.CompletedTime != nil {
		return *x.CompletedTime
	}
	return 0
}

func (x *TaskInput) GetSubtasks() []*CheckboxInput {
	if x != nil {
		return x.Subtasks
	}
	return nil
}

func (x *TaskInput) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *TaskInput) GetDeadline() int64 {
	if x != nil && x.Deadline != nil {
		return *x.Deadline
	}
	return 0
}

type TaskInputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskInput           `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInputs) Reset() {
	*x = TaskInputs{}
	mi := &file_core_task_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInputs) ProtoMessage() {}

func (x *TaskInputs) ProtoReflect() protoreflect.Message {
	mi := &file_core_task_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInputs.ProtoReflect.Descriptor instead.
func (*TaskInputs) Descriptor() ([]byte, []int) {
	return file_core_task_message_proto_rawDescGZIP(), []int{3}
}

func (x *TaskInputs) GetTasks() []*TaskInput {
	if x != nil {
		return x.Tasks
	}
	return nil
}

var File_core_task_message_proto protoreflect.FileDescriptor

const file_core_task_message_proto_rawDesc = "" +
	"\n" +
	"\x17core/task_message.proto\x12\x04core\x1a\x1bcore/checkbox_message.proto\"\xb0\x03\n" +
	"\aTaskMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x12!\n" +
	"\fcharacter_id\x18\x04 \x01(\tR\vcharacterId\x12$\n" +
	"\vcategory_id\x18\x05 \x01(\tH\x00R\n" +
	"categoryId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12*\n" +
	"\x0ecompleted_time\x18\b \x01(\x03H\x01R\rcompletedTime\x88\x01\x01\x12*\n" +
	"\bsubtasks\x18\t \x03(\v2\x0e.core.CheckboxR\bsubtasks\x12%\n" +
	"\vdescription\x18\n" +
	" \x01(\tH\x02R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\bdeadline\x18\v \x01(\x03H\x03R\bdeadline\x88\x01\x01B\x0e\n" +
	"\f_category_idB\x11\n" +
	"\x0f_completed_timeB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_deadline\"/\n" +
	"\bTaskMsgs\x12#\n" +
	"\x05tasks\x18\x01 \x03(\v2\r.core.TaskMsgR\x05tasks\"\xe2\x02\n" +
	"\tTaskInput\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12$\n" +
	"\vcategory_id\x18\x02 \x01(\tH\x01R\n" +
	"categoryId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12*\n" +
	"\x0ecompleted_time\x18\x05 \x01(\x03H\x02R\rcompletedTime\x88\x01\x01\x12/\n" +
	"\bsubtasks\x18\x06 \x03(\v2\x13.core.CheckboxInputR\bsubtasks\x12%\n" +
	"\vdescription\x18\a \x01(\tH\x03R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\bdeadline\x18\b \x01(\x03H\x04R\bdeadline\x88\x01\x01B\x05\n" +
	"\x03_idB\x0e\n" +
	"\f_category_idB\x11\n" +
	"\x0f_completed_timeB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_deadline\"3\n" +
	"\n" +
	"TaskInputs\x12%\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0f.core.TaskInputR\x05tasksB\x19Z\x17tenkhours/proto/pb/coreb\x06proto3"

var (
	file_core_task_message_proto_rawDescOnce sync.Once
	file_core_task_message_proto_rawDescData []byte
)

func file_core_task_message_proto_rawDescGZIP() []byte {
	file_core_task_message_proto_rawDescOnce.Do(func() {
		file_core_task_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_task_message_proto_rawDesc), len(file_core_task_message_proto_rawDesc)))
	})
	return file_core_task_message_proto_rawDescData
}

var file_core_task_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_core_task_message_proto_goTypes = []any{
	(*TaskMsg)(nil),       // 0: core.TaskMsg
	(*TaskMsgs)(nil),      // 1: core.TaskMsgs
	(*TaskInput)(nil),     // 2: core.TaskInput
	(*TaskInputs)(nil),    // 3: core.TaskInputs
	(*Checkbox)(nil),      // 4: core.Checkbox
	(*CheckboxInput)(nil), // 5: core.CheckboxInput
}
var file_core_task_message_proto_depIdxs = []int32{
	4, // 0: core.TaskMsg.subtasks:type_name -> core.Checkbox
	0, // 1: core.TaskMsgs.tasks:type_name -> core.TaskMsg
	5, // 2: core.TaskInput.subtasks:type_name -> core.CheckboxInput
	2, // 3: core.TaskInputs.tasks:type_name -> core.TaskInput
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_core_task_message_proto_init() }
func file_core_task_message_proto_init() {
	if File_core_task_message_proto != nil {
		return
	}
	file_core_checkbox_message_proto_init()
	file_core_task_message_proto_msgTypes[0].OneofWrappers = []any{}
	file_core_task_message_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_task_message_proto_rawDesc), len(file_core_task_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_task_message_proto_goTypes,
		DependencyIndexes: file_core_task_message_proto_depIdxs,
		MessageInfos:      file_core_task_message_proto_msgTypes,
	}.Build()
	File_core_task_message_proto = out.File
	file_core_task_message_proto_goTypes = nil
	file_core_task_message_proto_depIdxs = nil
}
