// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: core/timetracking_message.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimeTracking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CharacterId   string                 `protobuf:"bytes,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	CategoryId    *string                `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	ReferenceId   *string                `protobuf:"bytes,4,opt,name=reference_id,json=referenceId,proto3,oneof" json:"reference_id,omitempty"`
	ReferenceType *EntityType            `protobuf:"varint,5,opt,name=reference_type,json=referenceType,proto3,enum=core.EntityType,oneof" json:"reference_type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Duration      int64                  `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeTracking) Reset() {
	*x = TimeTracking{}
	mi := &file_core_timetracking_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeTracking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeTracking) ProtoMessage() {}

func (x *TimeTracking) ProtoReflect() protoreflect.Message {
	mi := &file_core_timetracking_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeTracking.ProtoReflect.Descriptor instead.
func (*TimeTracking) Descriptor() ([]byte, []int) {
	return file_core_timetracking_message_proto_rawDescGZIP(), []int{0}
}

func (x *TimeTracking) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TimeTracking) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *TimeTracking) GetCategoryId() string {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return ""
}

func (x *TimeTracking) GetReferenceId() string {
	if x != nil && x.ReferenceId != nil {
		return *x.ReferenceId
	}
	return ""
}

func (x *TimeTracking) GetReferenceType() EntityType {
	if x != nil && x.ReferenceType != nil {
		return *x.ReferenceType
	}
	return EntityType_TaskType
}

func (x *TimeTracking) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TimeTracking) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type TimeTrackingInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferenceId   *string                `protobuf:"bytes,1,opt,name=reference_id,json=referenceId,proto3,oneof" json:"reference_id,omitempty"`
	ReferenceType *EntityType            `protobuf:"varint,2,opt,name=reference_type,json=referenceType,proto3,enum=core.EntityType,oneof" json:"reference_type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Duration      int64                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeTrackingInput) Reset() {
	*x = TimeTrackingInput{}
	mi := &file_core_timetracking_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeTrackingInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeTrackingInput) ProtoMessage() {}

func (x *TimeTrackingInput) ProtoReflect() protoreflect.Message {
	mi := &file_core_timetracking_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeTrackingInput.ProtoReflect.Descriptor instead.
func (*TimeTrackingInput) Descriptor() ([]byte, []int) {
	return file_core_timetracking_message_proto_rawDescGZIP(), []int{1}
}

func (x *TimeTrackingInput) GetReferenceId() string {
	if x != nil && x.ReferenceId != nil {
		return *x.ReferenceId
	}
	return ""
}

func (x *TimeTrackingInput) GetReferenceType() EntityType {
	if x != nil && x.ReferenceType != nil {
		return *x.ReferenceType
	}
	return EntityType_TaskType
}

func (x *TimeTrackingInput) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TimeTrackingInput) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_core_timetracking_message_proto protoreflect.FileDescriptor

const file_core_timetracking_message_proto_rawDesc = "" +
	"\n" +
	"\x1fcore/timetracking_message.proto\x12\x04core\x1a\x1ecore/entity_type_message.proto\"\xbb\x02\n" +
	"\fTimeTracking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcharacter_id\x18\x02 \x01(\tR\vcharacterId\x12$\n" +
	"\vcategory_id\x18\x03 \x01(\tH\x00R\n" +
	"categoryId\x88\x01\x01\x12&\n" +
	"\freference_id\x18\x04 \x01(\tH\x01R\vreferenceId\x88\x01\x01\x12<\n" +
	"\x0ereference_type\x18\x05 \x01(\x0e2\x10.core.EntityTypeH\x02R\rreferenceType\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bduration\x18\a \x01(\x03R\bdurationB\x0e\n" +
	"\f_category_idB\x0f\n" +
	"\r_reference_idB\x11\n" +
	"\x0f_reference_type\"\xd7\x01\n" +
	"\x11TimeTrackingInput\x12&\n" +
	"\freference_id\x18\x01 \x01(\tH\x00R\vreferenceId\x88\x01\x01\x12<\n" +
	"\x0ereference_type\x18\x02 \x01(\x0e2\x10.core.EntityTypeH\x01R\rreferenceType\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x03R\bdurationB\x0f\n" +
	"\r_reference_idB\x11\n" +
	"\x0f_reference_typeB\x19Z\x17tenkhours/proto/pb/coreb\x06proto3"

var (
	file_core_timetracking_message_proto_rawDescOnce sync.Once
	file_core_timetracking_message_proto_rawDescData []byte
)

func file_core_timetracking_message_proto_rawDescGZIP() []byte {
	file_core_timetracking_message_proto_rawDescOnce.Do(func() {
		file_core_timetracking_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_timetracking_message_proto_rawDesc), len(file_core_timetracking_message_proto_rawDesc)))
	})
	return file_core_timetracking_message_proto_rawDescData
}

var file_core_timetracking_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_timetracking_message_proto_goTypes = []any{
	(*TimeTracking)(nil),      // 0: core.TimeTracking
	(*TimeTrackingInput)(nil), // 1: core.TimeTrackingInput
	(EntityType)(0),           // 2: core.EntityType
}
var file_core_timetracking_message_proto_depIdxs = []int32{
	2, // 0: core.TimeTracking.reference_type:type_name -> core.EntityType
	2, // 1: core.TimeTrackingInput.reference_type:type_name -> core.EntityType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_timetracking_message_proto_init() }
func file_core_timetracking_message_proto_init() {
	if File_core_timetracking_message_proto != nil {
		return
	}
	file_core_entity_type_message_proto_init()
	file_core_timetracking_message_proto_msgTypes[0].OneofWrappers = []any{}
	file_core_timetracking_message_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_timetracking_message_proto_rawDesc), len(file_core_timetracking_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_timetracking_message_proto_goTypes,
		DependencyIndexes: file_core_timetracking_message_proto_depIdxs,
		MessageInfos:      file_core_timetracking_message_proto_msgTypes,
	}.Build()
	File_core_timetracking_message_proto = out.File
	file_core_timetracking_message_proto_goTypes = nil
	file_core_timetracking_message_proto_depIdxs = nil
}
