package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"tenkhours/services/core/repo"
)

// Characters is the resolver for the characters field.
func (r *profileResolver) Characters(ctx context.Context, obj *repo.Profile) ([]repo.Character, error) {
	return r.CharactersBusiness.CharactersRepo.GetCharactersByProfileID(obj.ID)
}

// Profile returns ProfileResolver implementation.
func (r *Resolver) Profile() ProfileResolver { return &profileResolver{r} }

type profileResolver struct{ *Resolver }
