package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"tenkhours/pkg/utils"
	"tenkhours/services/core/graph/model"
	"tenkhours/services/core/graph/validations"
	"tenkhours/services/core/repo"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.ProfileInput) (*repo.Profile, error) {
	// Validate the input
	if err := validations.ValidateProfileInput(input); err != nil {
		return nil, err
	}

	return r.ProfilesBusiness.UpdateProfile(ctx, input)
}

// DeleteProfile is the resolver for the deleteProfile field.
func (r *mutationResolver) DeleteProfile(ctx context.Context) (*repo.Profile, error) {
	return r.ProfilesBusiness.DeleteProfile(ctx)
}

// UpsertCharacter is the resolver for the upsertCharacter field.
func (r *mutationResolver) UpsertCharacter(ctx context.Context, input model.CharacterInput) (*repo.Character, error) {
	// Validate the input
	if err := validations.ValidateCharacterInput(input); err != nil {
		return nil, err
	}

	return r.CharactersBusiness.UpsertCharacter(ctx, input)
}

// DeleteCharacter is the resolver for the deleteCharacter field.
func (r *mutationResolver) DeleteCharacter(ctx context.Context, id primitive.ObjectID) (*repo.Character, error) {
	return r.CharactersBusiness.DeleteCharacter(ctx, id)
}

// UpsertGoal is the resolver for the upsertGoal field.
func (r *mutationResolver) UpsertGoal(ctx context.Context, characterID primitive.ObjectID, input model.GoalInput) (*repo.Goal, error) {
	// Validate the input
	if err := validations.ValidateGoalInput(input); err != nil {
		return nil, err
	}

	return r.GoalsBusiness.UpsertGoal(ctx, characterID, input)
}

// Characters is the resolver for the characters field.
func (r *queryResolver) Characters(ctx context.Context) ([]repo.Character, error) {
	return r.CharactersBusiness.GetCharactersByProfileID(ctx)
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context) (*repo.Profile, error) {
	return r.ProfilesBusiness.GetProfile(ctx)
}

// AppSettings is the resolver for the appSettings field.
func (r *queryResolver) AppSettings(ctx context.Context) (*model.AppSettings, error) {
	return &model.AppSettings{
		MinDurationTime:       utils.MinDurationTime,
		MaxDurationTime:       utils.MaxDurationTime,
		LimitedMetricNumber:   utils.LimitedMetricNumber,
		LimitedPropertyNumber: utils.LimitedPropertyNumber,
	}, nil
}

// Goals is the resolver for the goals field.
func (r *queryResolver) Goals(ctx context.Context, characterID primitive.ObjectID, status *repo.GoalStatusFilter) ([]repo.Goal, error) {
	return r.GoalsBusiness.GetGoals(ctx, characterID, status)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
