package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"tenkhours/services/analytics_v2/graph/model"
)

// CreateSnapshot is the resolver for the createSnapshot field.
func (r *mutationResolver) CreateSnapshot(ctx context.Context, characterID string) (*model.Snapshot, error) {
	snapshot, err := r.CharactersHandler.CreateNewSnapshot(ctx, characterID)
	if err != nil {
		return nil, fmt.Errorf("failed to create snapshot: %v", err)
	}

	return mapModelToDto(snapshot), nil
}

// CharacterSnapshots is the resolver for the characterSnapshots field.
func (r *queryResolver) CharacterSnapshots(ctx context.Context, characterID string) ([]model.Snapshot, error) {
	snapshots, err := r.CharactersHandler.GetSnapshotsByCharacterID(ctx, characterID)
	if err != nil {
		return nil, fmt.Errorf("failed to get snapshots by character ID: %v", err)
	}

	var res []model.Snapshot
	for _, snapshot := range snapshots {
		res = append(res, *mapModelToDto(&snapshot))
	}

	return res, nil
}

// UserSnapshots is the resolver for the userSnapshots field.
func (r *queryResolver) UserSnapshots(ctx context.Context) ([]model.Snapshot, error) {
	snapshots, err := r.CharactersHandler.GetSnapshotsByProfileID(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get snapshots by character ID: %v", err)
	}

	var res []model.Snapshot
	for _, snapshot := range snapshots {
		res = append(res, *mapModelToDto(&snapshot))
	}

	return res, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
