// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"tenkhours/services/core/repo"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// Input for creating or updating a character.
type CharacterInput struct {
	// The name of the character.
	Name *string `json:"name,omitempty"`
	// Male is true, Female is false. Defaults to false.
	Gender *bool `json:"gender,omitempty"`
	// List of string tags that describe the character.
	Tags []string `json:"tags,omitempty"`
}

// Input for defining a custom metric.
type CustomMetricInput struct {
	// The name of the custom metric.
	Name *string `json:"name,omitempty"`
	// Description of the custom metric.
	Description *string `json:"description,omitempty"`
	// Visual style of the metric displayed on screen.
	Style *MetricStyleInput `json:"style,omitempty"`
	// List of properties that describe the metric.
	Properties []MetricPropertyInput `json:"properties,omitempty"`
}

// Input for defining a property of a custom metric.
type MetricPropertyInput struct {
	// ID of the property. If not provided, a new property will be created.
	ID *primitive.ObjectID `json:"id,omitempty"`
	// Name of the property.
	Name *string `json:"name,omitempty"`
	// Data type of the property (STRING or NUMBER).
	Type *repo.MetricPropertyType `json:"type,omitempty"`
	// Specific value of the property based on its data type.
	Value *string `json:"value,omitempty"`
	// Unit of the property value (e.g., seconds, meters, etc.).
	Unit *string `json:"unit,omitempty"`
}

// Input for specifying the visual style of a metric.
type MetricStyleInput struct {
	// Color of the metric, in Hex format.
	Color *string `json:"color,omitempty"`
	// URL or file path of the icon for the metric.
	Icon *string `json:"icon,omitempty"`
}

type Mutation struct {
}

// Input type for creating or updating a user profile.
type ProfileInput struct {
	// The name of the user.
	Name *string `json:"name,omitempty"`
	// URL of the user's image.
	ImageURL *string `json:"imageURL,omitempty"`
	// ID of the character currently being chosen by the user.
	CurrentCharacterID *string `json:"currentCharacterID,omitempty"`
	// Whether the user has enabled auto snapshot, default is true
	AutoSnapshot *bool `json:"autoSnapshot,omitempty"`
}

type Query struct {
}
