// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CharacterInput struct {
	Name   *string  `json:"name,omitempty"`
	Gender *bool    `json:"gender,omitempty"`
	Tags   []string `json:"tags,omitempty"`
}

type CustomMetricInput struct {
	Name        *string               `json:"name,omitempty"`
	Description *string               `json:"description,omitempty"`
	Style       *MetricStyleInput     `json:"style,omitempty"`
	Properties  []MetricPropertyInput `json:"properties,omitempty"`
}

type MetricPropertyInput struct {
	Name  *string `json:"name,omitempty"`
	Type  *string `json:"type,omitempty"`
	Value *string `json:"value,omitempty"`
	Unit  *string `json:"unit,omitempty"`
}

type MetricStyleInput struct {
	Color *string `json:"color,omitempty"`
	Icon  *string `json:"icon,omitempty"`
}

type Mutation struct {
}

type ProfileInput struct {
	Name               *string `json:"name,omitempty"`
	ImageURL           *string `json:"imageURL,omitempty"`
	CurrentCharacterID *string `json:"currentCharacterID,omitempty"`
	AutoSnapshot       *bool   `json:"autoSnapshot,omitempty"`
}

type Query struct {
}
