package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"
)

// AddToWaitlist is the resolver for the addToWaitlist field.
func (r *mutationResolver) AddToWaitlist(ctx context.Context, email string) (bool, error) {
	err := r.NotificationBusiness.AddEmailToWaitlist(ctx, email)
	if err != nil {
		fmt.Println("Failed to add email to waitlist:", err)
		return false, err
	}

	return true, nil
}

// Test is the resolver for the test field.
func (r *queryResolver) Test(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: Test - test"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
